<?php
//每个国家产品
$cat_duiying = array (

	'US'=>array(
	  249  => array('cat_name'=> "Cell Phones /Mobiles > WiFi Cell Phones",    'gender'=> '', 'title'=>'china cell phone',  'google_product_category'=> 'Electronics > Communications > Telephony > Mobile Phones'),
	  181  => array('cat_name'=> "Cell Phones /Mobiles > TV Cell Phones",      'gender'=> '', 'title'=>'china cell phone',  'google_product_category'=> 'Electronics > Communications > Telephony > Mobile Phones'),
	  270  => array('cat_name'=> "Cell Phones /Mobiles > Special Price Phones",'gender'=> '', 'title'=>'china cell phone',  'google_product_category'=> 'Electronics > Communications > Telephony > Mobile Phones'),
	  248  => array('cat_name'=> "Cell Phones /Mobiles > Smart Phones & PDA",  'gender'=> '', 'title'=>'unlocked phones',   'google_product_category'=> 'Electronics > Communications > Telephony > Mobile Phones'),
	  182  => array('cat_name'=> "Cell Phones /Mobiles > Quad Band Phones",    'gender'=> '', 'title'=>'cheap cell phones', 'google_product_category'=> 'Electronics > Communications > Telephony > Mobile Phones'),
	  167  => array('cat_name'=> "Cell Phones /Mobiles > Hot Phones",          'gender'=> '', 'title'=>'cheap cell phones', 'google_product_category'=> 'Electronics > Communications > Telephony > Mobile Phones'),
	  188  => array('cat_name'=> "Cell Phones /Mobiles > Dual Band Phones",    'gender'=> '', 'title'=>'cheap cell phones', 'google_product_category'=> 'Electronics > Communications > Telephony > Mobile Phones'),
	  505  => array('cat_name'=> "Cell Phones /Mobiles > China Best Phones",   'gender'=> '', 'title'=>'china cell phone',  'google_product_category'=> 'Electronics > Communications > Telephony > Mobile Phones'),
	  183  => array('cat_name'=> "Cell Phones /Mobiles > Cell Phone Watch",    'gender'=> '', 'title'=>'cheap cell phones', 'google_product_category'=> 'Electronics > Communications > Telephony > Mobile Phones'),
	  630  => array('cat_name'=> "Cell Phones /Mobiles > Android Phones",      'gender'=> '', 'title'=>'unlocked phones',   'google_product_category'=> 'Electronics > Communications > Telephony > Mobile Phones'),		  
	  1820  => array('cat_name'=> "Cell Phones /Mobiles > Android Phones",     'gender'=> '', 'title'=>'unlocked phones',   'google_product_category'=> 'Electronics > Communications > Telephony > Mobile Phones'),
	  1753  => array('cat_name'=> "Cell Phones /Mobiles > Android Phones",     'gender'=> '', 'title'=>'unlocked phones',   'google_product_category'=> 'Electronics > Communications > Telephony > Mobile Phones'),		  
	  1748 => array('cat_name'=> "Cell Phones /Mobiles > Unlocked Cell Phones",'gender'=> '', 'title'=>'unlocked phones',   'google_product_category'=> 'Electronics > Communications > Telephony > Mobile Phones'),
	  1818 => array('cat_name'=> "Cell Phones /Mobiles > Phablet",             'gender'=> '', 'title'=>'china cell phone',  'google_product_category'=> 'Electronics > Communications > Telephony > Mobile Phones'),
	  504  => array('cat_name'=> "Cell Phones /Mobiles > QWERTY Cell Phones",  'gender'=> '', 'title'=>'cheap cell phones', 'google_product_category'=> 'Electronics > Communications > Telephony > Mobile Phones'),
	  1780 => array('cat_name'=> "Cell Phones /Mobiles > GSM Phone",           'gender'=> '', 'title'=>'china cell phone',  'google_product_category'=> 'Electronics > Communications > Telephony > Mobile Phones'),
	  1781 => array('cat_name'=> "Cell Phones /Mobiles > Dual Sim Mobile Phones",'gender'=> '','title'=>'cheap cell phones','google_product_category'=> 'Electronics > Communications > Telephony > Mobile Phones'),
	  1779 => array('cat_name'=> "Cell Phones /Mobiles > Touch Screen Phones", 'gender'=> '', 'title'=>'unlocked phones',   'google_product_category'=> 'Electronics > Communications > Telephony > Mobile Phones'),		  		  		  		  		  		  		  
	  598  => array('cat_name'=> "Notebook/Tablet PC > Refurbished Tablet",    'gender'=> '', 'title'=>'cheap tablets',     'google_product_category'=> 'Electronics > Computers > Tablet Computers'),
	  453  => array('cat_name'=> "Notebook/Tablet PC > Android Os Tablet",     'gender'=> '', 'title'=>'cheap tablets',     'google_product_category'=> 'Electronics > Computers > Tablet Computers'),
	  1819 => array('cat_name'=> "Notebook/Tablet PC > Android 4.2 Tablet",    'gender'=> '', 'title'=>'cheap tablets',     'google_product_category'=> 'Electronics > Computers > Tablet Computers'),
	  1747 => array('cat_name'=> "Notebook/Tablet PC > Android 4.1 Tablet",    'gender'=> '', 'title'=>'cheap tablets',     'google_product_category'=> 'Electronics > Computers > Tablet Computers'),
	  1624 => array('cat_name'=> "Notebook/Tablet PC > Android 4.0 Tablet",    'gender'=> '', 'title'=>'cheap tablets',     'google_product_category'=> 'Electronics > Computers > Tablet Computers'),
	  1755 => array('cat_name'=> "Notebook/Tablet PC > Tablet Under $100",     'gender'=> '', 'title'=>'cheap tablets',     'google_product_category'=> 'Electronics > Computers > Tablet Computers'),
	  1815 => array('cat_name'=> "Notebook/Tablet PC > China Best Tablets",    'gender'=> '', 'title'=>'cheap tablets',     'google_product_category'=> 'Electronics > Computers > Tablet Computers'),
	  432  => array('cat_name'=> "Notebook/Tablet PC > 7 inch Tablet",         'gender'=> '', 'title'=>'cheap tablets',     'google_product_category'=> 'Electronics > Computers > Tablet Computers'),
	  1716 => array('cat_name'=> "Notebook/Tablet PC > Tablet Phone",          'gender'=> '', 'title'=>'cheap tablets',     'google_product_category'=> 'Electronics > Computers > Tablet Computers'),		  		  		  		  
	  421  => array('cat_name'=> "Notebook/Tablet PC > Notebook",              'gender'=> '', 'title'=>'android notebooks', 'google_product_category'=> 'Electronics > Computers > Laptops'),
	  1720 => array('cat_name'=> "Notebook/Tablet PC > Windows Os Tablet",     'gender'=> '', 'title'=>'android notebooks', 'google_product_category'=> 'Electronics > Computers > Laptops'),		  
	  410  => array('cat_name'=> "Consumer Electronics > Cameras & Camcorders>Digital Camcorders", 'gender'=> '', 'title'=>'camcorders', 'google_product_category'=> 'Cameras & Optics > Cameras> Digital Cameras'),
	  152  => array('cat_name'=> "Consumer Electronics > Cameras & Camcorders> High Megapixel Digital Cameras", 'gender'=> '', 'title'=>'cameras', 'google_product_category'=> 'Cameras & Optics > Cameras> Digital Cameras'),	  		  
	  ),


	'AU'=>array(
	  249  => array('cat_name'=> "Cell Phones /Mobiles > WiFi Cell Phones",    'gender'=> '', 'title'=>'android phones',      'google_product_category'=> 'Electronics > Communications > Telephony > Mobile Phones'),
	  181  => array('cat_name'=> "Cell Phones /Mobiles > TV Cell Phones",      'gender'=> '', 'title'=>'cheap mobile phones', 'google_product_category'=> 'Electronics > Communications > Telephony > Mobile Phones'),
	  270  => array('cat_name'=> "Cell Phones /Mobiles > Special Price Phones",'gender'=> '', 'title'=>'cheap mobile phones', 'google_product_category'=> 'Electronics > Communications > Telephony > Mobile Phones'),
	  248  => array('cat_name'=> "Cell Phones /Mobiles > Smart Phones & PDA",  'gender'=> '', 'title'=>'android phones',      'google_product_category'=> 'Electronics > Communications > Telephony > Mobile Phones'),
	  182  => array('cat_name'=> "Cell Phones /Mobiles > Quad Band Phones",    'gender'=> '', 'title'=>'cheap mobile phones', 'google_product_category'=> 'Electronics > Communications > Telephony > Mobile Phones'),
	  167  => array('cat_name'=> "Cell Phones /Mobiles > Hot Phones",          'gender'=> '', 'title'=>'cheap mobile phones', 'google_product_category'=> 'Electronics > Communications > Telephony > Mobile Phones'),
	  188  => array('cat_name'=> "Cell Phones /Mobiles > Dual Band Phones",    'gender'=> '', 'title'=>'cheap mobile phones', 'google_product_category'=> 'Electronics > Communications > Telephony > Mobile Phones'),
	  505  => array('cat_name'=> "Cell Phones /Mobiles > China Best Phones",   'gender'=> '', 'title'=>'android phones',      'google_product_category'=> 'Electronics > Communications > Telephony > Mobile Phones'),
	  183  => array('cat_name'=> "Cell Phones /Mobiles > Cell Phone Watch",    'gender'=> '', 'title'=>'cheap mobile phones', 'google_product_category'=> 'Electronics > Communications > Telephony > Mobile Phones'),
	  630  => array('cat_name'=> "Cell Phones /Mobiles > Android Phones",      'gender'=> '', 'title'=>'unlocked phones',   'google_product_category'=> 'Electronics > Communications > Telephony > Mobile Phones'),		  
	  1820  => array('cat_name'=> "Cell Phones /Mobiles > Android Phones",     'gender'=> '', 'title'=>'unlocked phones',   'google_product_category'=> 'Electronics > Communications > Telephony > Mobile Phones'),
	  1753  => array('cat_name'=> "Cell Phones /Mobiles > Android Phones",     'gender'=> '', 'title'=>'unlocked phones',   'google_product_category'=> 'Electronics > Communications > Telephony > Mobile Phones'),
	  1748 => array('cat_name'=> "Cell Phones /Mobiles > Unlocked Cell Phones",'gender'=> '', 'title'=>'android phones',      'google_product_category'=> 'Electronics > Communications > Telephony > Mobile Phones'),
	  1818 => array('cat_name'=> "Cell Phones /Mobiles > Phablet",             'gender'=> '', 'title'=>'android phones',      'google_product_category'=> 'Electronics > Communications > Telephony > Mobile Phones'),
	  504  => array('cat_name'=> "Cell Phones /Mobiles > QWERTY Cell Phones",  'gender'=> '', 'title'=>'cheap mobile phones', 'google_product_category'=> 'Electronics > Communications > Telephony > Mobile Phones'),
	  1780 => array('cat_name'=> "Cell Phones /Mobiles > GSM Phone",           'gender'=> '', 'title'=>'android phones',      'google_product_category'=> 'Electronics > Communications > Telephony > Mobile Phones'),
	  1781 => array('cat_name'=> "Cell Phones /Mobiles > Dual Sim Mobile Phones",'gender'=> '','title'=>'cheap mobile phones','google_product_category'=> 'Electronics > Communications > Telephony > Mobile Phones'),
	  1779 => array('cat_name'=> "Cell Phones /Mobiles > Touch Screen Phones", 'gender'=> '', 'title'=>'android phones',      'google_product_category'=> 'Electronics > Communications > Telephony > Mobile Phones'),		  		  		  		  		  		  		  
	  598  => array('cat_name'=> "Notebook/Tablet PC > Refurbished Tablet",    'gender'=> '', 'title'=>'cheap tablets',       'google_product_category'=> 'Electronics > Computers > Tablet Computers'),
	  453  => array('cat_name'=> "Notebook/Tablet PC > Android Os Tablet",     'gender'=> '', 'title'=>'cheap tablets',       'google_product_category'=> 'Electronics > Computers > Tablet Computers'),
	  1819 => array('cat_name'=> "Notebook/Tablet PC > Android 4.2 Tablet",    'gender'=> '', 'title'=>'android tablet',      'google_product_category'=> 'Electronics > Computers > Tablet Computers'),
	  1747 => array('cat_name'=> "Notebook/Tablet PC > Android 4.1 Tablet",    'gender'=> '', 'title'=>'android tablet',      'google_product_category'=> 'Electronics > Computers > Tablet Computers'),
	  1624 => array('cat_name'=> "Notebook/Tablet PC > Android 4.0 Tablet",    'gender'=> '', 'title'=>'cheap tablets',       'google_product_category'=> 'Electronics > Computers > Tablet Computers'),
	  1755 => array('cat_name'=> "Notebook/Tablet PC > Tablet Under $100",     'gender'=> '', 'title'=>'cheap tablets',       'google_product_category'=> 'Electronics > Computers > Tablet Computers'),
	  1815 => array('cat_name'=> "Notebook/Tablet PC > China Best Tablets",    'gender'=> '', 'title'=>'android tablet',      'google_product_category'=> 'Electronics > Computers > Tablet Computers'),
	  432  => array('cat_name'=> "Notebook/Tablet PC > 7 inch Tablet",         'gender'=> '', 'title'=>'android tablet',      'google_product_category'=> 'Electronics > Computers > Tablet Computers'),
	  1716 => array('cat_name'=> "Notebook/Tablet PC > Tablet Phone",          'gender'=> '', 'title'=>'android tablet',      'google_product_category'=> 'Electronics > Computers > Tablet Computers'),		  		  		  		  
	  421  => array('cat_name'=> "Notebook/Tablet PC > Notebook",              'gender'=> '', 'title'=>'android notebooks',   'google_product_category'=> 'Electronics > Computers > Laptops'),
	  1720 => array('cat_name'=> "Notebook/Tablet PC > Windows Os Tablet",     'gender'=> '', 'title'=>'android notebooks',   'google_product_category'=> 'Electronics > Computers > Laptops'),		  
	  410  => array('cat_name'=> "Consumer Electronics > Cameras & Camcorders>Digital Camcorders", 'gender'=> '', 'title'=>'camcorders', 'google_product_category'=> 'Cameras & Optics > Cameras> Digital Cameras'),
	  152  => array('cat_name'=> "Consumer Electronics > Cameras & Camcorders> High Megapixel Digital Cameras", 'gender'=> '', 'title'=>'cameras', 'google_product_category'=> 'Cameras & Optics > Cameras> Digital Cameras'),
	  ),

	'CA'=>array(
	  249  => array('cat_name'=> "Cell Phones /Mobiles > WiFi Cell Phones",    'gender'=> '', 'title'=>'cheap cell phones',  'google_product_category'=> 'Electronics > Communications > Telephony > Mobile Phones'),
	  181  => array('cat_name'=> "Cell Phones /Mobiles > TV Cell Phones",      'gender'=> '', 'title'=>'cheap cell phones',  'google_product_category'=> 'Electronics > Communications > Telephony > Mobile Phones'),
	  270  => array('cat_name'=> "Cell Phones /Mobiles > Special Price Phones",'gender'=> '', 'title'=>'cheap cell phones',  'google_product_category'=> 'Electronics > Communications > Telephony > Mobile Phones'),
	  248  => array('cat_name'=> "Cell Phones /Mobiles > Smart Phones & PDA",  'gender'=> '', 'title'=>'cheap smartphones',  'google_product_category'=> 'Electronics > Communications > Telephony > Mobile Phones'),
	  182  => array('cat_name'=> "Cell Phones /Mobiles > Quad Band Phones",    'gender'=> '', 'title'=>'cheap cell phones',  'google_product_category'=> 'Electronics > Communications > Telephony > Mobile Phones'),
	  167  => array('cat_name'=> "Cell Phones /Mobiles > Hot Phones",          'gender'=> '', 'title'=>'cheap cell phones',  'google_product_category'=> 'Electronics > Communications > Telephony > Mobile Phones'),
	  188  => array('cat_name'=> "Cell Phones /Mobiles > Dual Band Phones",    'gender'=> '', 'title'=>'cheap cell phones',  'google_product_category'=> 'Electronics > Communications > Telephony > Mobile Phones'),
	  505  => array('cat_name'=> "Cell Phones /Mobiles > China Best Phones",   'gender'=> '', 'title'=>'china phones',       'google_product_category'=> 'Electronics > Communications > Telephony > Mobile Phones'),
	  183  => array('cat_name'=> "Cell Phones /Mobiles > Cell Phone Watch",    'gender'=> '', 'title'=>'cheap cell phones',  'google_product_category'=> 'Electronics > Communications > Telephony > Mobile Phones'),
	  630  => array('cat_name'=> "Cell Phones /Mobiles > Android Phones",      'gender'=> '', 'title'=>'unlocked phones',   'google_product_category'=> 'Electronics > Communications > Telephony > Mobile Phones'),		  
	  1820  => array('cat_name'=> "Cell Phones /Mobiles > Android Phones",     'gender'=> '', 'title'=>'unlocked phones',   'google_product_category'=> 'Electronics > Communications > Telephony > Mobile Phones'),
	  1753  => array('cat_name'=> "Cell Phones /Mobiles > Android Phones",     'gender'=> '', 'title'=>'unlocked phones',   'google_product_category'=> 'Electronics > Communications > Telephony > Mobile Phones'),
	  1748 => array('cat_name'=> "Cell Phones /Mobiles > Unlocked Cell Phones",'gender'=> '', 'title'=>'cheap cell phones',  'google_product_category'=> 'Electronics > Communications > Telephony > Mobile Phones'),
	  1818 => array('cat_name'=> "Cell Phones /Mobiles > Phablet",             'gender'=> '', 'title'=>'china phones',       'google_product_category'=> 'Electronics > Communications > Telephony > Mobile Phones'),
	  504  => array('cat_name'=> "Cell Phones /Mobiles > QWERTY Cell Phones",  'gender'=> '', 'title'=>'cheap cell phones',  'google_product_category'=> 'Electronics > Communications > Telephony > Mobile Phones'),
	  1780 => array('cat_name'=> "Cell Phones /Mobiles > GSM Phone",           'gender'=> '', 'title'=>'china phones',       'google_product_category'=> 'Electronics > Communications > Telephony > Mobile Phones'),
	  1781 => array('cat_name'=> "Cell Phones /Mobiles > Dual Sim Mobile Phones",'gender'=> '','title'=>'cheap cell phones', 'google_product_category'=> 'Electronics > Communications > Telephony > Mobile Phones'),
	  1779 => array('cat_name'=> "Cell Phones /Mobiles > Touch Screen Phones", 'gender'=> '', 'title'=>'cheap smartphones',  'google_product_category'=> 'Electronics > Communications > Telephony > Mobile Phones'),		  		  		  		  		  		  		  
	  598  => array('cat_name'=> "Notebook/Tablet PC > Refurbished Tablet",    'gender'=> '', 'title'=>'cheap tablets',      'google_product_category'=> 'Electronics > Computers > Tablet Computers'),
	  453  => array('cat_name'=> "Notebook/Tablet PC > Android Os Tablet",     'gender'=> '', 'title'=>'cheap tablets',      'google_product_category'=> 'Electronics > Computers > Tablet Computers'),
	  1819 => array('cat_name'=> "Notebook/Tablet PC > Android 4.2 Tablet",    'gender'=> '', 'title'=>'andorid tablets',    'google_product_category'=> 'Electronics > Computers > Tablet Computers'),
	  1747 => array('cat_name'=> "Notebook/Tablet PC > Android 4.1 Tablet",    'gender'=> '', 'title'=>'andorid tablets',    'google_product_category'=> 'Electronics > Computers > Tablet Computers'),
	  1624 => array('cat_name'=> "Notebook/Tablet PC > Android 4.0 Tablet",    'gender'=> '', 'title'=>'cheap tablets',      'google_product_category'=> 'Electronics > Computers > Tablet Computers'),
	  1755 => array('cat_name'=> "Notebook/Tablet PC > Tablet Under $100",     'gender'=> '', 'title'=>'cheap tablets',      'google_product_category'=> 'Electronics > Computers > Tablet Computers'),
	  1815 => array('cat_name'=> "Notebook/Tablet PC > China Best Tablets",    'gender'=> '', 'title'=>'andorid tablets',    'google_product_category'=> 'Electronics > Computers > Tablet Computers'),
	  432  => array('cat_name'=> "Notebook/Tablet PC > 7 inch Tablet",         'gender'=> '', 'title'=>'andorid tablets',    'google_product_category'=> 'Electronics > Computers > Tablet Computers'),
	  1716 => array('cat_name'=> "Notebook/Tablet PC > Tablet Phone",          'gender'=> '', 'title'=>'andorid tablets',    'google_product_category'=> 'Electronics > Computers > Tablet Computers'),		  		  		  		  
	  421  => array('cat_name'=> "Notebook/Tablet PC > Notebook",              'gender'=> '', 'title'=>'android notebooks',  'google_product_category'=> 'Electronics > Computers > Laptops'),
	  1720 => array('cat_name'=> "Notebook/Tablet PC > Windows Os Tablet",     'gender'=> '', 'title'=>'android notebooks',  'google_product_category'=> 'Electronics > Computers > Laptops'),		  
	  410  => array('cat_name'=> "Consumer Electronics > Cameras & Camcorders>Digital Camcorders", 'gender'=> '', 'title'=>'camcorders', 'google_product_category'=> 'Cameras & Optics > Cameras> Digital Cameras'),
	  152  => array('cat_name'=> "Consumer Electronics > Cameras & Camcorders> High Megapixel Digital Cameras", 'gender'=> '', 'title'=>'cameras', 'google_product_category'=> 'Cameras & Optics > Cameras> Digital Cameras'),	
	),

	'UK'=>array(
	  249  => array('cat_name'=> "Cell Phones /Mobiles > WiFi Cell Phones",    'gender'=> '', 'title'=>'cheap phones',      'google_product_category'=> 'Electronics > Communications > Telephony > Mobile Phones'),
	  181  => array('cat_name'=> "Cell Phones /Mobiles > TV Cell Phones",      'gender'=> '', 'title'=>'cheap phones',      'google_product_category'=> 'Electronics > Communications > Telephony > Mobile Phones'),
	  270  => array('cat_name'=> "Cell Phones /Mobiles > Special Price Phones",'gender'=> '', 'title'=>'cheap phones',      'google_product_category'=> 'Electronics > Communications > Telephony > Mobile Phones'),
	  248  => array('cat_name'=> "Cell Phones /Mobiles > Smart Phones & PDA",  'gender'=> '', 'title'=>'cheap smartphones', 'google_product_category'=> 'Electronics > Communications > Telephony > Mobile Phones'),
	  182  => array('cat_name'=> "Cell Phones /Mobiles > Quad Band Phones",    'gender'=> '', 'title'=>'cheap phones',      'google_product_category'=> 'Electronics > Communications > Telephony > Mobile Phones'),
	  167  => array('cat_name'=> "Cell Phones /Mobiles > Hot Phones",          'gender'=> '', 'title'=>'cheap phones',      'google_product_category'=> 'Electronics > Communications > Telephony > Mobile Phones'),
	  188  => array('cat_name'=> "Cell Phones /Mobiles > Dual Band Phones",    'gender'=> '', 'title'=>'cheap phones',      'google_product_category'=> 'Electronics > Communications > Telephony > Mobile Phones'),
	  505  => array('cat_name'=> "Cell Phones /Mobiles > China Best Phones",   'gender'=> '', 'title'=>'china phones',      'google_product_category'=> 'Electronics > Communications > Telephony > Mobile Phones'),
	  183  => array('cat_name'=> "Cell Phones /Mobiles > Cell Phone Watch",    'gender'=> '', 'title'=>'cheap phones',      'google_product_category'=> 'Electronics > Communications > Telephony > Mobile Phones'),
	  630  => array('cat_name'=> "Cell Phones /Mobiles > Android Phones",      'gender'=> '', 'title'=>'unlocked phones',   'google_product_category'=> 'Electronics > Communications > Telephony > Mobile Phones'),		  
	  1820  => array('cat_name'=> "Cell Phones /Mobiles > Android Phones",     'gender'=> '', 'title'=>'unlocked phones',   'google_product_category'=> 'Electronics > Communications > Telephony > Mobile Phones'),
	  1753  => array('cat_name'=> "Cell Phones /Mobiles > Android Phones",     'gender'=> '', 'title'=>'unlocked phones',   'google_product_category'=> 'Electronics > Communications > Telephony > Mobile Phones'),
	  1748 => array('cat_name'=> "Cell Phones /Mobiles > Unlocked Cell Phones",'gender'=> '', 'title'=>'cheap phones',      'google_product_category'=> 'Electronics > Communications > Telephony > Mobile Phones'),
	  1818 => array('cat_name'=> "Cell Phones /Mobiles > Phablet",             'gender'=> '', 'title'=>'cheap smartphones', 'google_product_category'=> 'Electronics > Communications > Telephony > Mobile Phones'),
	  504  => array('cat_name'=> "Cell Phones /Mobiles > QWERTY Cell Phones",  'gender'=> '', 'title'=>'cheap phones',      'google_product_category'=> 'Electronics > Communications > Telephony > Mobile Phones'),
	  1780 => array('cat_name'=> "Cell Phones /Mobiles > GSM Phone",           'gender'=> '', 'title'=>'cheap smartphones', 'google_product_category'=> 'Electronics > Communications > Telephony > Mobile Phones'),
	  1781 => array('cat_name'=> "Cell Phones /Mobiles > Dual Sim Mobile Phones",'gender'=> '','title'=>'cheap phones',     'google_product_category'=> 'Electronics > Communications > Telephony > Mobile Phones'),
	  1779 => array('cat_name'=> "Cell Phones /Mobiles > Touch Screen Phones", 'gender'=> '', 'title'=>'cheap smartphones', 'google_product_category'=> 'Electronics > Communications > Telephony > Mobile Phones'),		  		  		  		  		  		  		  
	  598  => array('cat_name'=> "Notebook/Tablet PC > Refurbished Tablet",    'gender'=> '', 'title'=>'tablet cheap',      'google_product_category'=> 'Electronics > Computers > Tablet Computers'),
	  453  => array('cat_name'=> "Notebook/Tablet PC > Android Os Tablet",     'gender'=> '', 'title'=>'tablet cheap',      'google_product_category'=> 'Electronics > Computers > Tablet Computers'),
	  1819 => array('cat_name'=> "Notebook/Tablet PC > Android 4.2 Tablet",    'gender'=> '', 'title'=>'tablet pc',         'google_product_category'=> 'Electronics > Computers > Tablet Computers'),
	  1747 => array('cat_name'=> "Notebook/Tablet PC > Android 4.1 Tablet",    'gender'=> '', 'title'=>'tablet pc',         'google_product_category'=> 'Electronics > Computers > Tablet Computers'),
	  1624 => array('cat_name'=> "Notebook/Tablet PC > Android 4.0 Tablet",    'gender'=> '', 'title'=>'tablet cheap',      'google_product_category'=> 'Electronics > Computers > Tablet Computers'),
	  1755 => array('cat_name'=> "Notebook/Tablet PC > Tablet Under $100",     'gender'=> '', 'title'=>'tablet cheap',      'google_product_category'=> 'Electronics > Computers > Tablet Computers'),
	  1815 => array('cat_name'=> "Notebook/Tablet PC > China Best Tablets",    'gender'=> '', 'title'=>'tablet pc',         'google_product_category'=> 'Electronics > Computers > Tablet Computers'),
	  432  => array('cat_name'=> "Notebook/Tablet PC > 7 inch Tablet",         'gender'=> '', 'title'=>'tablet pc',         'google_product_category'=> 'Electronics > Computers > Tablet Computers'),
	  1716 => array('cat_name'=> "Notebook/Tablet PC > Tablet Phone",          'gender'=> '', 'title'=>'tablet pc',         'google_product_category'=> 'Electronics > Computers > Tablet Computers'),		  		  		  		  
	  421  => array('cat_name'=> "Notebook/Tablet PC > Notebook",              'gender'=> '', 'title'=>'android notebooks', 'google_product_category'=> 'Electronics > Computers > Laptops'),
	  1720 => array('cat_name'=> "Notebook/Tablet PC > Windows Os Tablet",     'gender'=> '', 'title'=>'android notebooks', 'google_product_category'=> 'Electronics > Computers > Laptops'),		  
	  410  => array('cat_name'=> "Consumer Electronics > Cameras & Camcorders>Digital Camcorders", 'gender'=> '', 'title'=>'camcorders', 'google_product_category'=> 'Cameras & Optics > Cameras> Digital Cameras'),
	  152  => array('cat_name'=> "Consumer Electronics > Cameras & Camcorders> High Megapixel Digital Cameras", 'gender'=> '', 'title'=>'cameras', 'google_product_category'=> 'Cameras & Optics > Cameras> Digital Cameras'),	
	)
);

?>