<?php
/**
 * filter_keyword.php       屏蔽搜索关键字
 *
 * @author                  wuwenlong mashanling(msl-138@163.com)
 * @date
 * @last modify             2012-09-03 17:38:52 by mashanling
 */

$fliter_key = array(
'windows',
'egon schiele cosmetics', 
'lt-6', 
    'sunglass',
    'sunglasses',
    'headphone',
    'headphones',
    'headset',
    'headsets',
    'earphone',
    'earphones',
    'lv',
    'd link',
    'power balance',
    'chanel',
    'ray ban',
    'ray ban',
    'oakley',
    'butterfly',
    'diesel time',
    'diesel',
    'bose',
    'beat',
    'spy',
    'cath kidston',
    'aviator',
    'mod chip',
    'stun gun',
    'cath',
    'kidston',
    'r4',
    'beats',
    'bird',
    'birds',
    'angry',
    'psp',

    'odm',
    'cig',//by mashanling on 2012 07 05 01:40:33

    'phillip lim',
    'phillip lims',
    'phillip',
    'ph lim',
    '3.1 phillip',
    '3.1 lim',
    '3.1 phillip lim lim',
    'for all mankind',
    'all mankind',
    '7 for mankind',
    'forallmankind',
    'allmankinds',
    '7mankinds',
    'seven for all mankind',
    'a lange sohne',
    'a. lange & sohnes',
    'a langesohen',
    'alange sohne',
    'circle pro',
    'abcircle pro',
    'abrocket',
    'ab rockets',
    'arocket',
    'brocket',
    'ab rock',
    'abockets',
    'abrocks',
    'ab rocketab',
    'abtronic',
    'abtronics',
    'tronic',
    'abercrombie',
    'abercrombie fitch',
    'af',
    'abercrombie&fitch',
    'a&f',
    'ab gyminic',
    'abgymics',
    'adida',
    'js (jeremy scott)',
    'adolfo',
    'domínguez',
    'a domínguez',
    'adolfodomínguezs',
    'adriana',
    'castros',
    'adrianacastro',
    'adrianacastros',
    'afflictions',
    'agnes',
    'airhogs',
    'hogs',
    'akademik',
    'akademikss',
    'akade',
    'akademikss',
    'akrispunto',
    'apunto',
    'a&punto',
    'apuntos',
    'apun',
    'akrissp',
    'albertaferretti',
    'ferretti',
    'a&ferretti',
    'alberta&ferretti',
    'alejandro',
    'ingelmo',
    'alejandro&ingelmo',
    'alexander',
    'mcqueen',
    'alexander&mcqueen',
    'alexandermcqueen',
    'amcqueen',
    'a&mcqueen',
    'alexandermcqueens',
    'alexanderwang',
    'alexanderw',
    'alexander wangss',
    'alexander&wang',
    'alfred',
    'angelo',
    'alfred&angelo',
    'alfreda',
    'alfredangelo',
    'aangelo',
    'olivia',
    'allsaint',
    'allsaint',
    'allsaintss',
    'all saint',
    'alpinestar',
    'alpinestarss',
    'amandapearl',
    'apearl',
    'aminaka',
    'wilmont',
    'aminakawilmont',
    'awilmonts',

    'a&molinari',
    'anna&molinari',
    'amolinari',
    'annamolinari',
    'annasui',
    'annas',
    'anna&sui',
    'anna su',
    'anneklein',
    'aklein',
    'anne kle',
    'anne',
    'ak',
    'nao',
    'shufle',
    'aquaglobes',
    'aqua&globes',
    'a&globes',
    'aquascutums',
    'aquascutumms',
    'aquasc',
    'aquascutuma',
    'aquascutums',
    'ax',
    'asicsasics',
    'audemars',
    'audemarspiguet',
    'ap',
    'ath headphone',
    'audio',
    'aussiebum',
    'azzedine&alaia',
    'azzedine alaiaalaia',
    'einstein',
    'babyleg',
    'baby legs',
    'xb',
    'balanciag',
    'ballys',
    'ballybally',
    'balmainn',
    'b & o',
    'milo',
    'battistonibattistoni',
    'bcbgb',
    'bcbgmaxa',
    'bcbbg',
    'bcbgmaxazria',
    'bbmaxazria',
    'beatrcie',
    'trussardi',
    'beatrcietrussardi',
    'b&t beatrcie',
    'beatrciet',
    'btrussardi',
    'beatrcietrussardi',
    'bellross',
    'bell and ross',
    'br',
    'bensherman',
    'b sherman',
    'ben shermans',
    'ben&sherman',
    'benefits',
    'berettas',
    'betsey&johnson',
    'betseyjohnson',
    'bjohnson',
    'bjohnsons',
    'bj',
    'betty',
    'boop',
    'bikkemberg',
    'bikkembergss',
    'billblass',
    'bill&blass',
    'bblass',
    'billb',
    'bill&blas',
    'billa bong',
    'billabongbill',
    'bbong',
    'billabongs',
    'billa&bong',
    'biothermm',
    'biotherms',
    'birkenstocks',
    'birkins',
    'blackberr',
    'b/b',
    'bb',
    'blancpains',

    'bobmackie',
    'bob&mackie',
    'bobbibrown',
    'bobbi&brown',
    'bbrown',
    'bobbi',
    'bo br',
    'bob',

    'bottegaveneta',
    'bottega&veneta',
    'bveneta',
    'bottegav',
    'b&v bottega',
    'b&veneta',
    'brazilbuttlift',
    'brazil butt',
    'brazil butt lifts',
    'breguetts',
    'breguetb',
    'breitlings',
    'brianatwood',
    'batwood',
    'brian&atwood',
    'briana',
    'b&atwood',
    'brian&atwoods',
    'bulovas',
    'bur.berry',
    'burbery',
    'burberr',
    'cacharell',
    'callaways',
    'hl irons',
    'jaws',
    'calvinklein',
    'calvin&klein',
    'klein',
    'calvin',
    'ck',
    'canada&goose',
    'canadag',
    'c&goose',
    'goose',
    'canada',
    'goose',
    'goose jacket',
    'carlota&alfaro',
    'c&alfaro',
    'carlotaalfaro',
    'carmen&marc valvo',
    'carmenmarcvalvo',
    'carmen marc',
    'marc valvo',
    'carmen marcvalvo',
    'c&marcvalvo',
    'carmen&marc',
    'carolina&herrera',
    'carolinah',
    'carolinaherrera',
    'cherrera',
    'c&herrera',
    'carolina perfume',
    'carreras',
    'cartiers',
    'casios',
    'kidston',
    'catherinemalandrino',
    'cmalandrino',
    'catherine&malandrino',
    'c&malandrino',
    'catherine',
    'malandrino',
    'catherinem',



    'chan',
    'double c',
    'cc',
    '4 ombres',
    'charleschang lima',
    'charles&chang lima',
    'charles&changl',
    'charles&chang&lima',
    'charlesdavid',
    'charles&david',
    'charlesd',
    'olympia',
    'chloe',
    'chopards',
    'chris&benz',
    'chrib',
    'chrisbenzs',
    'chrisben',
    'cbenz',
    'chris&b',
    'c&benz',
    'christian&audiger',
    'christianaudiger',
    'caudiger',
    'christian&dior',
    'dior christian dior',
    'c&dior',
    'cd',
    'christianlacroix',
    'christian&lacroix',
    'lacroix',
    'christian',
    'christianl',
    'cl louboutins',
    'christianlouboutin',
    'christian&louboutin',
    'c & louboutin',
    'cl',
    'chrisian',
    'christial l',
    'christian',
    'louboutin',
    'chronoswisses',
    'chronoswis',
    'chronosswiss',
    'citizens',
    'clarin',
    'cliniques',
    'cliniquee',
    'coaches',
    'coca',
    'cola',
    'cobras',
    'colehan',
    'cole&haan',
    'colehaan',
    'colin&stuart',
    'colins',
    'cstuarts',
    'c&stuart',
    'collette&dinnigan',
    'colletted',
    'collettedinnigan',
    'collette dinnigan',
    'collette',
    'dinnigan',
    'cdg',
    'play cdg',

    'corts',
    'corumm',
    'corums',
    'creatives',
    'cristóbal&balenciaga',
    'cristóbalbalenciaga',
    'cristóbal',
    'balenciaga',
    'crocss',
    'crocscrocs',
    'cynthiarowley',
    'cynthia&rowley',
    'cynthia',
    'rowley',
    'danabuchman',
    'dbuchman',
    'danielroth',
    'daniell roth',
    'davidoffdavidoff',
    'dcshoes',
    'dc shoes',
    'dc&shoes',
    'dcsshoes',

    'dereklam',
    'derek lam',
    'derek&lam',
    'dlam',
    'diadoraa',
    'dvf',
    'dianevonfurstenberg',
    'frstenberg',
    'diese',
    'diesell',
    'digi stor',
    'digi&stor',
    'stordigi stor',
    'homm',
    'homme',
    'the walt disney company',
    'disney dvd',
    'dknys',
    'd k n y',
    'dolce and gabbana',
    'dolce gabbana',
    'dolce gabbana',
    'dg',
    'donna and karan',
    'donnakaran',
    'karan',
    'donna',
    'db',
    'dooney burke',
    'dooneyburkes',
    'd*b',
    'dvn',
    'driesvannoten',
    'dries',
    'van',
    'noten',
    'driesvan',
    'vannoten',
    'dsquared',
    'dsq2',
    'ducati',
    'cati',
    'ducat',
    'ucati',
    'ducham',
    'ducham',
    'duchamps',
    'dunhi',
    'dunh',
    'unhill',
    'dunhil',
    'dunill',
    'dvf',
    'd vf',
    'd v f',
    'dvf d',
    'ebels',
    'ecko',
    'eck',
    'eckos',
    'eckos',
    'hardy',
    'edhardys',
    'edhardy',
    'ehardy',
    'edhard',
    'edardy',
    'ehardy',
    'edhard',
    'el primeros',
    'element',
    'eleykishimoto',
    'eley',
    'kishimoto',
    'eley kishimotos',
    'leykishimo',
    'eleykhimoto',
    'beth arden',
    'elsaschiaparelli',
    'elsa',
    'schiaparelli',
    'elsaschiapare',
    'schiaparellis',
    'elschiaparelli',
    'eschiaparelli',
    'emilio',
    'pucci',
    'emiliopuccci',
    'emporio ar',
    'emporio arm',
    'armani',
    'gio',
    'emporio',
    'energi',
    'nergie',
    'energi',
    'ener',
    'energies',
    'energie',
    'enricocoveri',
    'enrico coverii',
    'eonons',
    'eoonon',
    'epso',
    'epsons',
    'pson',
    'ericksonbeamon',
    'erickson',
    'beamon',
    'ericksons',
    'beamons',
    'ericksonbeamons',
    'escad',
    'escadas',
    'escadai',
    'escadaii',
    'escadal',
    'esca',
    'eescada',
    'escadaa',
    'espri',
    'sprit',
    'espr',
    'eprit',
    'esprits',
    'esteelauder',
    'estees',
    'lauders',
    'esteelauders',
    'estee&lauder',
    'estee and lauder',
    'aigner',
    'evisus',
    'evisui',
    'evi',
    'eviisu',
    'evisuu',
    'fender',
    'fendar',
    'fende',
    'fenders',
    'fendes',
    'feder',
    'fenderr',
    'eric clapton strat',
    'sunburst',
    'fend',
    'fendii',
    'feendi',
    'farraggamo',
    'farragam',
    'farragamos',
    'farraga',
    'farragam',
    'faragamo',
    'frragamo',
    'farragmo',
    'ferrarii',
    'ferrarie',
    'ferrarri',
    'fil',
    'fla',
    'filas',
    'filaa',
    'fische',
    'fischerr',
    'fisch',
    'fischer',
    'fischerf',
    'fjallrave',
    'fjallravenn',
    'fjallravens',
    'fjallrav',
    'fjalraven',
    'fjllrave',
    'footjoy',
    'foot joy',
    'foot',
    'joy',
    'footjoyy',
    'fotjoy',
    'footj',
    'footjoys',
    'f21',

    'frankmuller',
    'frank mullers',
    'frankmullers',
    'francomoschino',
    'franco moschin',
    'francmoschino',
    'francomoschii',
    'franco moschinos',
    'franco',
    'moschino',
    'franklin & marshall',
    'fred leightons',
    'fredleighton',
    'fredleighto',
    'fredleight',
    'fredl',
    'fredleightons',
    'fred',
    'leighton',
    'fred',
    'perry',
    'fredperry',
    'fredperryy',
    'fredpery',
    'freperry',
    'gaia',
    'pervoinni',
    'gaia pervoinn',
    'gaiapervoinni',
    'gaia & pervoinni',
    'gaia pervoinnis',
    'galliano',
    'gallian',
    'gallianoo',
    'gallianos',
    'ggalliano',
    'gal liano',
    'gants',
    'gantt',
    'ganttt',
    'gann',
    'ganti',
    'gaps',
    'gapp',
    'ggap',
    'gapgap',
    'gareth',
    'pugh',
    'garethpugh',
    'garethpughs',
    'garethpug',
    'gareth pughh',
    'gareths',
    'pughs',
    'firebird',
    'lp (les paul)',
    'giorgio',
    'geraldgenta',
    'gerald gentaa',
    'geren',
    'ford',
    'gerenford',
    'gerenord',
    'gerenfords',
    'gereford',
    'geen ford',
    'gereford',
    'ghds',
    'mk4',
    'ghdd',
    'ghd1',
    'ghdghd',
    'mk5',
    'giambattista vall',
    'giambattista valll',
    'giambattista',
    'valli',
    'giambattistas',
    'valli',
    'giambattistavalli',
    'gianfranco',
    'ferré',
    'gianfrancoferré',
    'gianfranco ferre',
    'gianfranco feré',
    'gianmarcolorenzi',
    'gianmarco lorenzii',
    'gianmarco lorenzie',
    'gibsons',
    'gibso',
    'gibs',
    'gibsonn',
    'gibsongibson',
    'gibsonso',
    '175',
    'ultra',
    'giuseppe zanotti',
    'givenchy',
    'givench',
    'givenchyy',
    'givenchyi',
    'givenc',
    'given chy',
    'gola',
    'gollaa',
    'gollas',
    'golla1',
    'gollai',
    'golia',
    'gollaai',
    'goretex',
    'gorete',
    'goretexx',
    'gorete',
    'goretx',
    'goyards',
    'goyardd',
    'goyar',
    'goyardr',
    'graemeblack',
    'graeme',
    'graemeblackk',
    'graemeblac',
    'graemelack',
    'graemblack',
    'graha',
    'grahams',
    'grahamm',
    'grahami',
    'grahamn',
    'gretsc',
    'gretscch',
    'gretschs',
    'gretssch',
    'gretschh',
    'gretschi',
    '6120',
    'grypho',
    'gryph',
    'gryphonn',
    'gryphons',
    'gryphom',
    'g star',
    'gstar',
    'g staraw',
    'gstarr',
    'g starraw',
    'g star raw',
    'g starr',
    'g starr raw',
    'gstarraw',
    'guuci',
    'guci',
    'guci',
    'gucc',
    'guesses',
    'guesss',
    'h20',
    'h220',
    'hach',
    'hachee',
    'haches',
    'hachees',
    'hachehache',
    'hacket',
    'hackettt',
    'hacktt',
    'hacketthackett',
    'haglof',
    'haglofss',
    'hagloffs',
    'haglfs',
    'hglofs',
    'haglofss',
    'hglofs',
    'haglos',
    'haiderackerman',
    'haider',
    'ackerman',
    'haider ackermann',
    'haiderackernnan',
    'hanae mori',
    'hanaemori',
    'hanae morii',
    'hanae morr',
    'hanae mori',
    'hanamori',
    'hanni yy',
    'hani y',
    'hanniy',
    'harleydavidson',
    'harley davidsons',
    'davidson',
    'harley',
    'hary winston',
    'harry winsston',

    'heads',
    'heead',
    'hr',
    'helena rubensteins',
    'helena',
    'helmuut lang',
    'hermers',
    'hermess',
    'herrmes',
    'herve legerr',
    'herrve leger',
    'herve',
    'herves',
    'hexbugs',
    'hex bug',
    'hex bugs',
    'hexxbug',
    'hogans',
    'hogann',
    'hoganss',
    'holister co',
    'hollister coo',

    'htcc',
    'httc',
    'desire',
    'hublothublot',
    'geneve',
    'hugo perfume',
    'hugo',
    'boss',
    'hydrolyzes',
    'hydrolyzee',
    'hydroxatones',
    'hydroxatonee',
    'hyundaii',
    'hyundaie',
    'ibanezz',
    'lbanez',
    'illusions bridal',
    'illusion bridal',
    'illusion veils',
    'illusion viels',
    'insanitty',
    'insanityy',
    'iphonee',


    'miyake',
    'iwwc',
    'iwcc',
    'schaffhausen',
    'jack jone',
    'jack jones',
    'jack wils',
    'jack will',
    'jacks wills',
    'demartini',
    'jacob co',
    'jaegerlecounltre',
    'jaegerllecoultre',
    'jason wuu',
    'jay goodfrey',

    'jean paul',
    'jean gaultier',
    'gaultier',
    'jeepp',
    'jeeps',
    'jeepjeep',
    'jlo',
    'jessica mcclintock',
    'jesica mcclintock',
    'jhane barrnes',
    'jhane barne',
    'jhane barnne',
    'jil saderr',
    'jilsander',
    'jil&sander',
    'jilsander',
    'jil sanderji',
    'jimy choo',
    'jimmy cho',
    'john galiano',
    'jonathan saunder',
    'jonathan saunderrs',
    'judith ripkas',
    'judth ripken',
    'judith ripkane',
    'judithripka',
    'judith&ripka',
    'juicycouture',
    'juicy coutures',
    'juicycoutures',
    'juicy c',
    'couture',
    'juicy',
    'junya wtanabe',
    'juny watanabes',
    'jwatanabe',
    'junyaw',
    'junya&watanabe',
    'jurliques',
    'jurliquee',
    'karen',
    'km',
    'millen',
    'karl lagerfen',
    'karl lagerfelds',
    'kar&lagerfeld',
    'karllagerfeld',
    'kate spades',
    'kate spaden',
    'kate&spade',
    'kate spade',
    'katespade',
    'kenneths',
    'kenneth coles',
    'kenneth&cole',
    'kennethcole',
    'kent& curwens',
    'kents& curwen',
    'kent & curwena',
    'kenzo takadas',
    'kenz takada',
    'kenzo takad',
    'kiehl',
    'kiehls',
    'kiehlss',
    'kiehl.s',
    'kimora lee simmon',
    'kingstone',
    'kingstons',
    'kingstones',
    'bag kitson',
    'kitson',
    'kitsons',
    'kitsonkitson',
    'koi suwannagates',
    'koobs',
    'koses',
    'koose',
    'kosses',
    'koes',
    'kungzhuzhu',
    'kung zhu',
    'loccitane',
    'll’occitane',
    'l oreal',
    'l’ooreal',
    'oreal',
    'la martinas',
    'las martina',
    'lamartina',
    'la martina',
    'la&martina',
    'la merr',
    'lamer',
    'lamerr',
    'lacostes',
    'laguna beash',
    'laguna bachs',
    'laguna beah',
    'laila azha',
    'lail azhar',
    'lailas azhar',
    'lancomes',
    'lancoome',
    'lancomee',
    'lane bryants',
    'lanes bryant',
    'lane bryan',
    'lange',
    'laura bennetts',
    'lauran bennett',
    'laura bennet',
    'laurens moffatt',
    'lauren moffat',
    'lauren moffatts',
    'le coq sprotifs',
    'le coqs sprotif',
    'lessportsac',
    'le sportsacc',
    'lees',
    "lee's",
    'leee',
    'leg avenues',
    'legs avenue',
    'leg avenuen',
    'lela rosen',
    'lelas rose',
    'lelan rose',
    'lela roses',
    'lesmill',
    'levis',
    'leuis',
    'leviss',
    'levs',
    'lida badays',
    'lidan baday',
    'lida bday',
    'lida bady',
    'linksoflondon',
    'link of london',
    'of london',
    'lisan perry',
    'lisa perr',
    'lisa parry',
    'lise perry',
    'lisa&perry',
    'liz claibornes',
    'liza claiborne',
    'lz claiborne',
    'liz claibore',
    'loeffler randalls',
    'loeffler randal',
    'loeffler&r',
    'longchamps',
    'longcham',
    'longchamplongchamp',
    'longine',
    'longin',
    'longins',
    'longiness',
    'lonsdalen',
    'lonsdall',
    'lonsdalls',
    'louisviution',
    'louis vitoon',
    'louis vuitons',
    'vuiton',
    'lv',
    'lvmh',
    'luigi loro pianan',
    'luig loro piana',
    'lylescott',
    'lyle scotts',
    'lyle scot',
    'macs',
    'maac',
    'macc',
    'm.a.c',
    'm a c',
    'mc',
    'dazzle',
    'mad shoe',
    'maggies sottero',
    'maggien sottero',
    'maggie sotten',
    'sottero',
    'makeupforever',
    'make up foreverr',
    'mammutt',
    'mammuts',
    'manan',
    'manaa',
    'manamana',
    'manly',
    'manolo blahnike',
    'manolo blahniks',
    'manolon blahnik',
    'maran hoffman',
    'mara hoffmans',
    'mara hoffmane',
    'marc jacob',
    'marc jacob',
    'marc jacobs',
    'marc&jacobs',
    'marcjacobs',
    'marcj',
    'marc',
    'marchesan',
    'marchesane',
    'marchesamarchesa',
    'marinela',
    'marinellan',
    'marinellam',
    'marinellamarinella',
    'martin',
    'martins grant',
    'martin grantt',
    'marti grant',
    'martin&grant',
    'masih zads',
    'masih zade',
    'masih zad',
    'masihz',
    'mzad',
    'masihzad',
    'maxfactor',
    'max factors',
    'max factorr',
    'factor',
    'max maa',
    'max mra',
    'max mar',
    'max mara',
    'mmara',
    'maybelines',
    'maybelline',
    'maybellines',
    'mbtt',
    'mbbt',
    'mbts',
    'merrells',
    'merrel',
    'mgms',
    'mcm',
    'mcms',
    'mgmmgm',
    'mgma',
    'mk',
    'microsofts',
    'mlcrosoft',
    'millets',
    'milles',
    'milletmillet',
    'mis sixty',
    'miss sixt',
    'misssixty',
    'mius',
    'miumiu',
    'miu&miu',
    'miu miu miu',
    'miu mi',
    'mizun',
    'mizunmizun',
    'mobiad',
    'mobiss',
    'moobis',
    'moltionbrown',
    'moltoon brown',
    'moltoon brown',
    'moncheribridals',
    'mon&cheribridals',
    'mon cheri bridals',
    'cheribridals',
    'mcheri bridals',
    'mcheribridals',
    'monclers',
    'mocleer',
    'monclerr',
    'monc',
    'monsters',
    'moonster',
    'dr dre',
    'beats by dr. dre',
    'beats',
    'beats by drdre',
    'gaga',
    'bieber',
    'by dre',
    'montblanc',
    'montt blanc',
    'mont blancc',
    'blanc',
    'mooncup',
    'blaze',
    'moto',
    'movad',
    'movadomovado',
    'movadomovado',
    'mulbery',
    'mulberymulbery',
    'mulberrym',
    'mydailydoses',
    'mydaillydose',
    'nanette lepor',
    'nanettelepore',
    'nanette&lepore',
    'nanettel',
    'nanette leporelepore',
    'narss',
    'narrs',
    'nbaa',
    'newbalance',
    'nbalance',
    'new&balance',
    'balance',
    'new&b',
    'nico didona',
    'nicodidonna',
    'nico&didonna',
    'ndidonna',
    'nicole',
    'aj shoe',
    'lebron',
    'shox',
    'max air',
    'j 25',
    'j 9',
    'j 2010',
    'j 10',
    'j 11',
    'j 13',
    'j 23',
    'j evolution 85',
    'max',
    'j5',
    'j4',
    'aj 3 retro',
    'retro',
    'j4',
    'j6',
    'nina',
    'ninaricci',
    'nina&ricci',
    'nina&r',
    'nricci',
    'nino ceruti',
    'nino&ceruti',
    'ninocerruti',
    'nino&c',
    'n&cerruti',
    'n&c nino',
    'ds lite',
    'ndsi (nintendo dsi)',
    'nokiia',
    'x6',
    'novala takemot',
    'novala&takemot',
    'novalatakemot',
    'novala&takemot',
    'nuxxe',
    'nuxes',
    'nuxee',
    'okley',
    'oakly',
    'oakleys',
    'okl',
    'oakleys',
    'okley',
    'oakly',
    'oak',
    'oddmolly',
    'odds molly',
    'odd mollyy',
    'omage',
    'omeg',
    'o m e ge',
    'opii',
    'orexiss',
    'orrexis',
    'oscardelarenta',
    'oscar de a renta',
    'oscardela',
    'ospreys',
    'ospprey',
    'otterbx',
    'otter box',
    'otterboxs',
    'otter',
    'p90',
    '90x',
    'extreme fitness',
    'paco chican',
    'pacochicano',
    'paco&chicano',
    'pacoc',
    'paco rabane',
    'paco&rabane',
    'pacorabane',
    'pando',
    'pandor',
    'pandorap',
    'panera',
    'panarai',
    'panarei',
    'paneraipanerai',
    'parmigianl',
    'parmiigiani',

    'patephilippe',
    'patek philipe',
    'patek philippes',
    'paul franks',
    'paulfrank',
    'paull frank',
    'paullfrank',
    'frank',
    'joe',
    'p shark',
    'paulshark',
    'paul&shark',
    'p smith',
    'paul s',
    'paulsmith',
    'paul&smith',
    'pb',
    'peek',
    'paek',
    'peakpeak',
    'paek',
    'izumi',
    'perry elis',
    'perry&elis',
    'perry',
    'perry&elli',
    'peter so',
    'peter&som',
    'peter som',
    'peutery',
    'peuteryy',
    'peuterypeutery',
    'phitens',
    'phitten',
    'phiiten',
    'piagets',
    'piagett',
    'plaget',
    'piazz sempione',
    'piazzsempione',
    'piazz&sempione',
    'piazz&s',
    'pioeers',
    'pioeerr',
    'pioneers',
    'pkgs',
    'polic',
    'poli',
    'policepolice',
    'polos',
    'polost',
    'poloo',
    'ponys',
    'ponyy',
    'ponie',
    'ponypony',
    'porsche',
    'prosches',
    'porschee',
    'powerranger',
    'power rangerr',
    'power rangerss',
    'power balances',
    'prad',
    'pra',
    'kennex',
    'pulsars',
    'pullsar',
    'pulsarr',
    'puma',
    'pumas',
    'pumma',
    'pumapuma',

    'radi',
    'raddi',
    'raddii',
    'radoo',
    'rados',
    'raado',
    'ralph',
    'lauren',
    'ralphlauren',
    'poloralphlauren',
    'rayban',
    'ray ban',
    'rayban',
    'rb',
    'ray',
    '3025',
    '3029',
    '3211',
    '3269',
    'rm watch',
    'richard watch',
    'mille watch',
    'rick owen',
    'rick owensrick r&owens',
    'robert clergeri',
    'robert clergere',
    'robert dane',
    'roberts danes',
    'roberto capuccii',
    'roberto capuci',
    'robin’s',
    'robin',
    'robinjeans',
    'robinjeans',

    'rock republic',
    'r&republic',
    'r&d',
    'rogerdubuis',
    'rogerr dubuis',
    'rostta',
    'rosettastone',
    'rosetta stones',
    'rosetta',
    'roundtree richardson',
    'angry',
    'roxys',
    'rozae nichol',
    'ruffle butts',
    'rufflebutt',
    'salvatore ferragamoo',
    'hello',
    'kitty',
    'scotch sodaa',
    'scottycameron',
    'scotty camerons',
    'sebagoo',
    'sebagos',
    'sebaago',

    'seikoo',
    'seikoseiko',
    'seikoseiko',
    'sennheisers',
    'sennherserr',
    'senheiser',
    'cx',
    'sergio rosi',
    'sherri',
    'hill',
    'shipley halmos',
    'shiple halmos',
    'shipley halmos',
    'shipleyhalmos',
    'shiseidos',
    'shiseeido',
    'shiseidoo',
    'shuunmura',
    'shu uemuras',
    'shu uemmura',
    'beta 58',
    'bandz',
    'silly',
    'sinful',
    'sinfulsinful',
    'sinfulsinful',
    'sisleys',
    'sislley',
    'sisleyss',
    'skiphop',
    'skiphops',
    'skip hops',
    'magic',
    'sleepywrap',
    'sleepwraps',
    'sixa',
    'axis',
    'six axis',
    '6 axis',
    'dual 3',
    'specilized',
    'spyderr',
    'spyders',
    'stefano pilatii',
    'stefano riccci',
    'stefano riicci',
    'senfano rici',
    'stella macartney',
    'stella mcccartney',
    'stela mccartney',
    'stella mccartneey',
    'stephen yearick',
    'stphen yeerick',
    'steve maden',
    'stones island',
    'strenessee',
    'streenesse',
    'strenesses',
    'stuart weitzmen',
    'stuat weetzman',
    'stuartweitzman',
    'stuart&weitzman',
    'submarinerr',
    'submarineer',
    'suprra',
    'supras',
    'swarovsk',
    'swarovskii',
    'swatches',
    'switch easy',
    'swittch easy',
    'swticheassy',
    'tag heuer',
    'tag heuers',
    'tag heuer',
    'taharri',
    'taharii',
    'tk',
    'tapoutt',
    'tappout',
    'tapouttapout',
    'tascos',
    'tascco',
    'tascoo',
    'made',
    'techdeck',
    'tech&deck',
    'tech deck',
    'ted bakers',
    'teds baker',
    'ted baker',
    'tedbaker',
    'temperrley',
    'thakoonthakoon',
    'north face',
    'nortth face',
    'norths face',
    'north faces',
    'tnf',
    'north',

    'thomas burrerry',
    'thomas burbery',
    'thomas pinks',
    'thomass pink',
    'thomas saboo',
    'sabo',
    'thomas',
    'thomas wyldes',
    'thomas wyldee',
    'thomas wyldee',
    'thomas wyllde',
    'tiffany co.',
    'tifany co.',
    'tifany & co',
    'tiffany coo',
    "tiffany's",
    'tifanny',
    'tiffanny',
    'tiffany',
    'tiffany co',
    'tiffani',
    'tiff & co',
    'tiffanys',
    'tiff',
    't & co',
    'tiss',
    'timberlands',
    'timbberland',
    'timberrland',
    'tbl',
    'todd oldhamm',
    'todds',
    'tods',
    'tomford',
    'tom & ford',
    'tommy hifigeer',
    'tommy',
    'hilfiger',
    'lamborghini',
    'topwells',
    'topwel',
    'tory burcch',
    'toryy burch',
    'tory burch',
    'burch',
    'tory',
    'tour',
    'edge',

    't religion',
    'trreligion',
    'tr ue religion',
    'true religion',
    'tr',
    'true religions',
    'trxx',
    'trrx',
    'trxs',
    't_e_s',
    't se',
    'tsetse',
    'tuleh',
    't uleh',
    "t'uleh",
    'tulehtuleh',
    'turbofires',
    'turbo fire',
    'truboflre',
    'boat',
    'ub',
    'ubio',
    'ubiiq',
    'ubiqs',
    'uggs',
    'ugg australia',
    'bailey',
    'ulyssenardin',
    'ullysse nardin',
    'ulyssenardiin',
    'u mbro',
    'um bro',
    'umbroumbro',
    'un garo',
    'v cube',
    'vv cube',
    'vacheron',
    'v constantin',
    'vacher on constantin',
    'valentino garava',
    'va garavani',
    'vanns',
    'vanss',
    'vaans',
    'velonys',
    'velonyys',
    'veloony',
    'vcava',
    'venacuran',
    'vera bradley',
    'verbradley',
    'vbradley',
    'verawang',
    'vera wangs',
    'veraawang',
    'vera',
    'wang',
    'veromoda',
    'vero madda',
    'veromooda',
    'ver sa ce',
    'ver sace',
    'v sace',
    'v ibram',
    'vibram',
    'victoria',
    'victoria secret',
    'victoria secret',
    "victoria's",
    'v ince',
    'v ince',
    'vincevince',
    'vivienee westwood',
    'vivi westwood',
    'vivienne w',
    'vivienne&westwood',
    'vivi west wood',
    'volki',
    'volkll',
    'voikl',
    'voiki',
    'vz',
    'washburns',
    'washburrn',
    'washburns',
    'west elms',
    'westelm',
    'wilsonwilson',
    'yamahaha',
    'yamahaa',
    'yammaha',
    'yohji ya',
    'yamamoto',
    'yohji yamamoto',
    'yohji&yamamoto',
    'yo yamamoto',
    'baby can read',
    'your baby read',
    'baby can read',
    'your baby can read',
    'your can read',
    'baby read',
    'baby can read',
    'your baby read',
    'baby can read',
    'your baby can read',
    'your can read',
    'baby read',
    'zac posen',
    'zac& posen',
    'zacposen',
    'za oosen',
    'zaccposen',
    'z ara',
    'zar',
    'zaraz',
    'z sport',
    'zegnas',
    'zegna sport',
    'ermenegildo',
    'z sport',
    'zegnas',
    'zegna sport',
    'zhuzhupet',
    'zhu zhu pets',
    'zhupets',
    'zippo',
    'zippoo',
    'zumb',
);