<?php
//后台自动生成，最后生成时间 2014-02-20 09:36:56
$data = array (
  45 => 
  array (
    'region_id' => '45',
    'region_code' => 'AF',
    'region_name' => 'Afghanistan',
    'payment' => ',WiredTransfer,PayPal,CreditCard,WesternUnion,webcollect,webmoney,DirectDebit,boletoBancario,BankTransfer',
    'shipping' => ',1,3',
    'code' => '93',
    'state' => 
    array (
      0 => 'aaaaaaaaaaaaaaaa',
      1 => 'bbbbbbbbbbbbb',
    ),
  ),
  244 => 
  array (
    'region_id' => '244',
    'region_code' => 'AX',
    'region_name' => 'Aland Islands',
    'payment' => ',WesternUnion,PayPal,CreditCard,WiredTransfer,webcollect',
    'shipping' => ',1,2,3',
    'code' => '',
    'state' => '',
  ),
  46 => 
  array (
    'region_id' => '46',
    'region_code' => 'AL',
    'region_name' => 'Albania',
    'payment' => ',WiredTransfer,WesternUnion,PayPal,CreditCard,webcollect',
    'shipping' => ',1',
    'code' => '355',
    'state' => '',
  ),
  47 => 
  array (
    'region_id' => '47',
    'region_code' => 'DZ',
    'region_name' => 'Algeria',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect',
    'shipping' => ',1,3',
    'code' => '213',
    'state' => '',
  ),
  48 => 
  array (
    'region_id' => '48',
    'region_code' => 'AS',
    'region_name' => 'American Samoa',
    'payment' => ',WesternUnion,PayPal,CreditCard,WiredTransfer,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '1684',
    'state' => '',
  ),
  49 => 
  array (
    'region_id' => '49',
    'region_code' => 'AD',
    'region_name' => 'Andorra',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '376',
    'state' => '',
  ),
  50 => 
  array (
    'region_id' => '50',
    'region_code' => 'AO',
    'region_name' => 'Angola',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1',
    'code' => '244',
    'state' => '',
  ),
  51 => 
  array (
    'region_id' => '51',
    'region_code' => 'AI',
    'region_name' => 'Anguilla',
    'payment' => ',WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '1264',
    'state' => '',
  ),
  245 => 
  array (
    'region_id' => '245',
    'region_code' => 'AQ',
    'region_name' => 'Antarctica',
    'payment' => ',PayPal,CreditCard,WesternUnion,WiredTransfer,webcollect,webcollect',
    'shipping' => ',1,2,3',
    'code' => '',
    'state' => '',
  ),
  54 => 
  array (
    'region_id' => '54',
    'region_code' => 'AG',
    'region_name' => 'Antigua and Barbuda',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '1268',
    'state' => '',
  ),
  55 => 
  array (
    'region_id' => '55',
    'region_code' => 'AR',
    'region_name' => 'Argentina',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,webcollect,webcollect,CreditCard',
    'shipping' => ',1,2,3',
    'code' => '54',
    'state' => '',
  ),
  56 => 
  array (
    'region_id' => '56',
    'region_code' => 'AM',
    'region_name' => 'Armenia',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1',
    'code' => '374',
    'state' => '',
  ),
  57 => 
  array (
    'region_id' => '57',
    'region_code' => 'AW',
    'region_name' => 'Aruba',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '297',
    'state' => '',
  ),
  11 => 
  array (
    'region_id' => '11',
    'region_code' => 'AU',
    'region_name' => 'Australia',
    'payment' => ',PayPal,WiredTransfer,WesternUnion,CreditCard,webcollect',
    'shipping' => ',3,1,2',
    'code' => '61',
    'state' => 
    array (
      0 => 'Australian Capital Territory',
      1 => 'New South Wales',
      2 => 'Northern Territory',
      3 => 'Queensland',
      4 => 'South Australia',
      5 => 'Tasmania',
      6 => 'Victoria',
      7 => 'Western Australia',
      8 => 'burgenland',
    ),
  ),
  58 => 
  array (
    'region_id' => '58',
    'region_code' => 'AT',
    'region_name' => 'Austria',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect',
    'shipping' => ',1,2,3',
    'code' => '',
    'state' => 
    array (
      0 => 'Burgenland',
      1 => 'Niedersterreich',
      2 => 'Oberosterreich',
      3 => 'Salzburg',
      4 => 'Steiermark',
      5 => 'Tirol',
      6 => 'Voralberg',
      7 => 'Wien',
      8 => 'karnten',
    ),
  ),
  59 => 
  array (
    'region_id' => '59',
    'region_code' => 'AZ',
    'region_name' => 'Azerbaijan',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1',
    'code' => '994',
    'state' => '',
  ),
  60 => 
  array (
    'region_id' => '60',
    'region_code' => 'BS',
    'region_name' => 'Bahamas',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect',
    'shipping' => ',1,3',
    'code' => '1242',
    'state' => '',
  ),
  61 => 
  array (
    'region_id' => '61',
    'region_code' => 'BH',
    'region_name' => 'Bahrain',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,2,3',
    'code' => '973',
    'state' => '',
  ),
  62 => 
  array (
    'region_id' => '62',
    'region_code' => 'BD',
    'region_name' => 'Bangladesh',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect',
    'shipping' => ',1,2,3',
    'code' => '880',
    'state' => '',
  ),
  63 => 
  array (
    'region_id' => '63',
    'region_code' => 'BB',
    'region_name' => 'Barbados',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect',
    'shipping' => ',1,3',
    'code' => '1246',
    'state' => '',
  ),
  64 => 
  array (
    'region_id' => '64',
    'region_code' => 'BY',
    'region_name' => 'Belarus',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard',
    'shipping' => ',1,2',
    'code' => '375',
    'state' => '',
  ),
  65 => 
  array (
    'region_id' => '65',
    'region_code' => 'BE',
    'region_name' => 'Belgium',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect',
    'shipping' => ',1,2,3',
    'code' => '32',
    'state' => '',
  ),
  66 => 
  array (
    'region_id' => '66',
    'region_code' => 'BZ',
    'region_name' => 'Belize',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '501',
    'state' => '',
  ),
  67 => 
  array (
    'region_id' => '67',
    'region_code' => 'BJ',
    'region_name' => 'Benin',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '229',
    'state' => '',
  ),
  68 => 
  array (
    'region_id' => '68',
    'region_code' => 'BM',
    'region_name' => 'Bermuda',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '1441',
    'state' => '',
  ),
  249 => 
  array (
    'region_id' => '249',
    'region_code' => 'BT',
    'region_name' => 'Bhutan',
    'payment' => ',PayPal,CreditCard,WesternUnion,WiredTransfer,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '975',
    'state' => '',
  ),
  69 => 
  array (
    'region_id' => '69',
    'region_code' => 'BO',
    'region_name' => 'Bolivia',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '591',
    'state' => '',
  ),
  252 => 
  array (
    'region_id' => '252',
    'region_code' => 'BQ',
    'region_name' => 'Bonaire',
    'payment' => ',PayPal,CreditCard,WesternUnion,WiredTransfer,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '',
    'state' => '',
  ),
  226 => 
  array (
    'region_id' => '226',
    'region_code' => 'BA',
    'region_name' => 'Bosnia and Herzegovina',
    'payment' => ',PayPal,CreditCard,WesternUnion,WiredTransfer,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '387',
    'state' => '',
  ),
  70 => 
  array (
    'region_id' => '70',
    'region_code' => 'BW',
    'region_name' => 'Botswana',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3,2',
    'code' => '267',
    'state' => '',
  ),
  253 => 
  array (
    'region_id' => '253',
    'region_code' => 'BV',
    'region_name' => 'Bouvet Island',
    'payment' => ',WiredTransfer,WesternUnion,CreditCard,PayPal,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '',
    'state' => '',
  ),
  12 => 
  array (
    'region_id' => '12',
    'region_code' => 'BR',
    'region_name' => 'Brazil',
    'payment' => ',PayPal,WiredTransfer,WesternUnion,CreditCard,Boleto',
    'shipping' => ',1,2,3',
    'code' => '55',
    'state' => '',
  ),
  256 => 
  array (
    'region_id' => '256',
    'region_code' => 'IO',
    'region_name' => 'British Indian Ocean Territory',
    'payment' => ',WiredTransfer,WesternUnion,CreditCard,PayPal,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '246',
    'state' => '',
  ),
  254 => 
  array (
    'region_id' => '254',
    'region_code' => 'BN',
    'region_name' => 'Brunei ',
    'payment' => ',WiredTransfer,WesternUnion,CreditCard,PayPal,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '673',
    'state' => '',
  ),
  72 => 
  array (
    'region_id' => '72',
    'region_code' => 'BG',
    'region_name' => 'Bulgaria',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3,2',
    'code' => '359',
    'state' => '',
  ),
  73 => 
  array (
    'region_id' => '73',
    'region_code' => 'BF',
    'region_name' => 'Burkina Faso',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,2,3',
    'code' => '226',
    'state' => '',
  ),
  74 => 
  array (
    'region_id' => '74',
    'region_code' => 'BI',
    'region_name' => 'Burundi',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '257',
    'state' => '',
  ),
  269 => 
  array (
    'region_id' => '269',
    'region_code' => 'KH',
    'region_name' => 'Cambodia',
    'payment' => ',WiredTransfer,CreditCard,WesternUnion,PayPal,webcollect,webcollect',
    'shipping' => ',1,2',
    'code' => '855',
    'state' => '',
  ),
  75 => 
  array (
    'region_id' => '75',
    'region_code' => 'CM',
    'region_name' => 'Cameroon',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard',
    'shipping' => ',1,3',
    'code' => '237',
    'state' => '',
  ),
  13 => 
  array (
    'region_id' => '13',
    'region_code' => 'CA',
    'region_name' => 'Canada',
    'payment' => ',PayPal,WiredTransfer,WesternUnion,CreditCard',
    'shipping' => ',1,2,3',
    'code' => '1',
    'state' => 
    array (
      0 => 'Alberta',
      1 => 'British Columbia',
      2 => 'Manitoba',
      3 => 'New Brunswick',
      4 => 'Newfoundland and Labrador',
      5 => 'Northwest Territories',
      6 => 'Nova Scotia',
      7 => 'Nunavut',
      8 => 'Ontario',
      9 => 'Prince Edward Island',
      10 => 'Quebec',
      11 => 'Saskatchewan',
      12 => 'Yukon',
    ),
  ),
  319 => 
  array (
    'region_id' => '319',
    'region_code' => 'IC',
    'region_name' => 'Canary Islands',
    'payment' => NULL,
    'shipping' => NULL,
    'code' => '',
    'state' => '',
  ),
  77 => 
  array (
    'region_id' => '77',
    'region_code' => 'CV',
    'region_name' => 'Cape Verde',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '238',
    'state' => '',
  ),
  79 => 
  array (
    'region_id' => '79',
    'region_code' => 'KY',
    'region_name' => 'Cayman Islands',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect',
    'shipping' => ',1,3,2',
    'code' => '1345',
    'state' => '',
  ),
  80 => 
  array (
    'region_id' => '80',
    'region_code' => 'CF',
    'region_name' => 'Central African Republic',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '236',
    'state' => '',
  ),
  81 => 
  array (
    'region_id' => '81',
    'region_code' => 'TD',
    'region_name' => 'Chad',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,2,3',
    'code' => '235',
    'state' => '',
  ),
  82 => 
  array (
    'region_id' => '82',
    'region_code' => 'CL',
    'region_name' => 'Chile',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard',
    'shipping' => ',1,3',
    'code' => '56',
    'state' => '',
  ),
  317 => 
  array (
    'region_id' => '317',
    'region_code' => 'CN',
    'region_name' => 'China',
    'payment' => ',PayPal,CreditCard,WesternUnion,WiredTransfer,webmoney,BankTransfer,boletoBancario',
    'shipping' => ',1',
    'code' => '86',
    'state' => '',
  ),
  271 => 
  array (
    'region_id' => '271',
    'region_code' => 'CX',
    'region_name' => 'Christmas Island',
    'payment' => ',WiredTransfer,WesternUnion,CreditCard,PayPal,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '61',
    'state' => '',
  ),
  272 => 
  array (
    'region_id' => '272',
    'region_code' => 'CC',
    'region_name' => 'Cocos (Keeling) Island',
    'payment' => ',WiredTransfer,WesternUnion,CreditCard,PayPal,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '61',
    'state' => '',
  ),
  14 => 
  array (
    'region_id' => '14',
    'region_code' => 'CO',
    'region_name' => 'Colombia',
    'payment' => ',PayPal,WiredTransfer,WesternUnion,CreditCard,webcollect',
    'shipping' => ',1,2,3',
    'code' => '57',
    'state' => '',
  ),
  273 => 
  array (
    'region_id' => '273',
    'region_code' => 'KM',
    'region_name' => 'Comoros',
    'payment' => ',WiredTransfer,WesternUnion,CreditCard,PayPal,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '269',
    'state' => '',
  ),
  275 => 
  array (
    'region_id' => '275',
    'region_code' => 'CG',
    'region_name' => 'CONGO',
    'payment' => ',WiredTransfer,WesternUnion,CreditCard,PayPal,webcollect,webcollect',
    'shipping' => ',1,2,3',
    'code' => '242',
    'state' => '',
  ),
  276 => 
  array (
    'region_id' => '276',
    'region_code' => 'CD',
    'region_name' => 'Congo, the Democratic Republic of',
    'payment' => ',WiredTransfer,WesternUnion,CreditCard,PayPal,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '243',
    'state' => '',
  ),
  277 => 
  array (
    'region_id' => '277',
    'region_code' => 'CK',
    'region_name' => 'Cook Islands',
    'payment' => ',WiredTransfer,WesternUnion,CreditCard,PayPal,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '682',
    'state' => '',
  ),
  89 => 
  array (
    'region_id' => '89',
    'region_code' => 'CR',
    'region_name' => 'Costa Rica',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '506',
    'state' => '',
  ),
  278 => 
  array (
    'region_id' => '278',
    'region_code' => 'CI',
    'region_name' => 'Cote D\'Ivoire',
    'payment' => ',PayPal,CreditCard,WesternUnion,WiredTransfer,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '',
    'state' => '',
  ),
  90 => 
  array (
    'region_id' => '90',
    'region_code' => 'HR',
    'region_name' => 'Croatia',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,2,3',
    'code' => '',
    'state' => '',
  ),
  91 => 
  array (
    'region_id' => '91',
    'region_code' => 'CU',
    'region_name' => 'Cuba',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,2,3',
    'code' => '',
    'state' => '',
  ),
  313 => 
  array (
    'region_id' => '313',
    'region_code' => 'XC',
    'region_name' => 'Curaco',
    'payment' => ',WiredTransfer,WesternUnion,CreditCard,PayPal,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '',
    'state' => '',
  ),
  15 => 
  array (
    'region_id' => '15',
    'region_code' => 'CY',
    'region_name' => 'Cyprus',
    'payment' => ',PayPal,WiredTransfer,WesternUnion,CreditCard,webcollect,webcollect',
    'shipping' => ',1,2,3',
    'code' => '357',
    'state' => '',
  ),
  94 => 
  array (
    'region_id' => '94',
    'region_code' => 'CZ',
    'region_name' => 'Czech Republic',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,2,3',
    'code' => '420',
    'state' => '',
  ),
  95 => 
  array (
    'region_id' => '95',
    'region_code' => 'DK',
    'region_name' => 'Denmark',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect',
    'shipping' => ',1,2,3',
    'code' => '45',
    'state' => '',
  ),
  96 => 
  array (
    'region_id' => '96',
    'region_code' => 'DJ',
    'region_name' => 'Djibouti',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,2,3',
    'code' => '253',
    'state' => '',
  ),
  286 => 
  array (
    'region_id' => '286',
    'region_code' => 'DM',
    'region_name' => 'Dominica',
    'payment' => ',PayPal,CreditCard,WesternUnion,WiredTransfer,webcollect',
    'shipping' => ',1,3',
    'code' => '1767',
    'state' => '',
  ),
  16 => 
  array (
    'region_id' => '16',
    'region_code' => 'DO',
    'region_name' => 'Dominican Republic',
    'payment' => ',PayPal,WiredTransfer,WesternUnion,CreditCard,webcollect',
    'shipping' => ',1,3',
    'code' => '1809',
    'state' => 
    array (
      0 => 'Ace Peyer Province',
      1 => 'Azua Province',
      2 => 'Baoru&nbsp;Province',
      3 => 'Barahona&nbsp;Province',
      4 => 'Daha friends&nbsp;Province',
      5 => 'Dominic&nbsp;provinces',
      6 => 'Duarte Province',
      7 => 'El seibo Province',
      8 => 'Ellis PIA Province',
      9 => 'Hato mayor Province',
      10 => 'Hermanas mirabal Province',
      11 => 'Independent province',
      12 => 'La Vega Province',
      13 => 'Maria Sanchez Province',
      14 => 'Monsignor Nouel Province',
      15 => 'Monte Cristi Province',
      16 => 'National district',
      17 => 'Pakistani province of Wade',
      18 => 'Pedernales Province',
      19 => 'Peravia Province',
      20 => 'Puerto Plata Province',
      21 => 'Rome Province',
      22 => 'Samana Province',
      23 => 'San Jose Province',
      24 => 'San Juan',
      25 => 'Sanchez Lummis Province',
      26 => 'Santiago - Rory gates Province',
      27 => 'Santiago.',
      28 => 'St. Peter Province',
      29 => 'St.&nbsp;Chris&nbsp;Fort&nbsp;Province',
      30 => 'The province',
      31 => 'Yinshan Province',
    ),
  ),
  97 => 
  array (
    'region_id' => '97',
    'region_code' => 'EC',
    'region_name' => 'Ecuador',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard',
    'shipping' => ',1,3',
    'code' => '593',
    'state' => '',
  ),
  17 => 
  array (
    'region_id' => '17',
    'region_code' => 'EG',
    'region_name' => 'Egypt',
    'payment' => ',PayPal,WiredTransfer,WesternUnion,CreditCard,webcollect,webcollect',
    'shipping' => ',1,2,3',
    'code' => '20',
    'state' => '',
  ),
  170 => 
  array (
    'region_id' => '170',
    'region_code' => 'SV',
    'region_name' => 'El Salvador',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '503',
    'state' => '',
  ),
  99 => 
  array (
    'region_id' => '99',
    'region_code' => 'GQ',
    'region_name' => 'Equitoral Guinea',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '240',
    'state' => '',
  ),
  291 => 
  array (
    'region_id' => '291',
    'region_code' => 'ER',
    'region_name' => 'Eritrea',
    'payment' => ',PayPal,CreditCard,WesternUnion,WiredTransfer,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '291',
    'state' => '',
  ),
  100 => 
  array (
    'region_id' => '100',
    'region_code' => 'EE',
    'region_name' => 'Estonia',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,2',
    'code' => '372',
    'state' => '',
  ),
  101 => 
  array (
    'region_id' => '101',
    'region_code' => 'ET',
    'region_name' => 'Ethiopia',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,2,3',
    'code' => '251',
    'state' => '',
  ),
  292 => 
  array (
    'region_id' => '292',
    'region_code' => 'FK',
    'region_name' => 'Falkland Islands (Malvinas)',
    'payment' => ',WesternUnion,WiredTransfer,CreditCard,PayPal,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '500',
    'state' => '',
  ),
  227 => 
  array (
    'region_id' => '227',
    'region_code' => 'FO',
    'region_name' => 'Faroe Islands',
    'payment' => ',PayPal,CreditCard,WesternUnion,WiredTransfer,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '298',
    'state' => '',
  ),
  102 => 
  array (
    'region_id' => '102',
    'region_code' => 'FJ',
    'region_name' => 'Fiji',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect',
    'shipping' => ',1,3',
    'code' => '679',
    'state' => '',
  ),
  224 => 
  array (
    'region_id' => '224',
    'region_code' => 'FI',
    'region_name' => 'Finland',
    'payment' => ',PayPal,WiredTransfer,WesternUnion,CreditCard,webcollect',
    'shipping' => ',1,2,3',
    'code' => '358',
    'state' => '',
  ),
  18 => 
  array (
    'region_id' => '18',
    'region_code' => 'FR',
    'region_name' => 'France',
    'payment' => ',PayPal,WiredTransfer,WesternUnion,CreditCard,webcollect',
    'shipping' => ',1,2,3',
    'code' => '33',
    'state' => '',
  ),
  294 => 
  array (
    'region_id' => '294',
    'region_code' => 'GF',
    'region_name' => 'French Guiana',
    'payment' => ',WiredTransfer,WesternUnion,CreditCard,PayPal,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '594',
    'state' => '',
  ),
  295 => 
  array (
    'region_id' => '295',
    'region_code' => 'PF',
    'region_name' => 'French Polynesia',
    'payment' => ',WiredTransfer,WesternUnion,CreditCard,PayPal,webcollect,webcollect',
    'shipping' => ',3',
    'code' => '689',
    'state' => '',
  ),
  296 => 
  array (
    'region_id' => '296',
    'region_code' => 'TF',
    'region_name' => 'French Southern Territories',
    'payment' => ',WiredTransfer,WesternUnion,CreditCard,PayPal,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '',
    'state' => '',
  ),
  104 => 
  array (
    'region_id' => '104',
    'region_code' => 'GA',
    'region_name' => 'Gabon',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,2,3',
    'code' => '241',
    'state' => '',
  ),
  105 => 
  array (
    'region_id' => '105',
    'region_code' => 'GM',
    'region_name' => 'Gambia',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '220',
    'state' => '',
  ),
  106 => 
  array (
    'region_id' => '106',
    'region_code' => 'GE',
    'region_name' => 'Georgia',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1',
    'code' => '995',
    'state' => '',
  ),
  19 => 
  array (
    'region_id' => '19',
    'region_code' => 'DE',
    'region_name' => 'Germany',
    'payment' => ',PayPal,WiredTransfer,WesternUnion,CreditCard,webcollect',
    'shipping' => ',1,2,3',
    'code' => '49',
    'state' => 
    array (
      0 => 'Baden-Wrttemberg',
      1 => 'Bayern',
      2 => 'Berlin',
      3 => 'Brandenburg',
      4 => 'Bremen',
      5 => 'Hamburg',
      6 => 'Hessen',
      7 => 'Mecklenburg-Vorpommern',
      8 => 'Niedersachsen',
      9 => 'Nordrhein-Westfalen',
      10 => 'Rheinland-Pfalz',
      11 => 'Saarland',
      12 => 'Sachsen',
      13 => 'Sachsen-Anhalt',
      14 => 'Schleswig-Holstein',
      15 => 'Thuringen',
    ),
  ),
  20 => 
  array (
    'region_id' => '20',
    'region_code' => 'GH',
    'region_name' => 'Ghana',
    'payment' => ',PayPal,WiredTransfer,WesternUnion,CreditCard',
    'shipping' => ',1,2,3',
    'code' => '233',
    'state' => '',
  ),
  108 => 
  array (
    'region_id' => '108',
    'region_code' => 'GI',
    'region_name' => 'Gibraltar',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '350',
    'state' => '',
  ),
  225 => 
  array (
    'region_id' => '225',
    'region_code' => 'GR',
    'region_name' => 'Greece',
    'payment' => ',PayPal,CreditCard,WesternUnion,WiredTransfer,webcollect',
    'shipping' => ',1,2',
    'code' => '30',
    'state' => '',
  ),
  109 => 
  array (
    'region_id' => '109',
    'region_code' => 'GL',
    'region_name' => 'Greenland',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '299',
    'state' => '',
  ),
  110 => 
  array (
    'region_id' => '110',
    'region_code' => 'GD',
    'region_name' => 'Grenada',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '1473',
    'state' => '',
  ),
  111 => 
  array (
    'region_id' => '111',
    'region_code' => 'GP',
    'region_name' => 'Guadeloupe',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '590',
    'state' => '',
  ),
  301 => 
  array (
    'region_id' => '301',
    'region_code' => 'GU',
    'region_name' => 'Guam',
    'payment' => ',PayPal,CreditCard,WesternUnion,WiredTransfer,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '1671',
    'state' => '',
  ),
  113 => 
  array (
    'region_id' => '113',
    'region_code' => 'GT',
    'region_name' => 'Guatemala',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '502',
    'state' => '',
  ),
  302 => 
  array (
    'region_id' => '302',
    'region_code' => 'GG',
    'region_name' => 'Guernsey',
    'payment' => ',CreditCard,WesternUnion,WiredTransfer,PayPal,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '44',
    'state' => '',
  ),
  114 => 
  array (
    'region_id' => '114',
    'region_code' => 'GN',
    'region_name' => 'Guinea',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,2,3',
    'code' => '224',
    'state' => '',
  ),
  115 => 
  array (
    'region_id' => '115',
    'region_code' => 'GW',
    'region_name' => 'Guinea Bissau',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '245',
    'state' => '',
  ),
  116 => 
  array (
    'region_id' => '116',
    'region_code' => 'GY',
    'region_name' => 'Guyana',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,2,3',
    'code' => '592',
    'state' => '',
  ),
  303 => 
  array (
    'region_id' => '303',
    'region_code' => 'HT',
    'region_name' => 'Haiti',
    'payment' => ',PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '509',
    'state' => '',
  ),
  305 => 
  array (
    'region_id' => '305',
    'region_code' => 'HM',
    'region_name' => 'Heard Island and McDonald Islands',
    'payment' => ',PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '',
    'state' => '',
  ),
  306 => 
  array (
    'region_id' => '306',
    'region_code' => 'VA',
    'region_name' => 'Holy See (Vatican City State)',
    'payment' => ',PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '379',
    'state' => '',
  ),
  117 => 
  array (
    'region_id' => '117',
    'region_code' => 'HN',
    'region_name' => 'Honduras',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '504',
    'state' => '',
  ),
  239 => 
  array (
    'region_id' => '239',
    'region_code' => 'HK',
    'region_name' => 'Hongkong',
    'payment' => ',PayPal,CreditCard,WesternUnion,WiredTransfer,webcollect,webcollect',
    'shipping' => ',1,2,3',
    'code' => '852',
    'state' => '',
  ),
  118 => 
  array (
    'region_id' => '118',
    'region_code' => 'HU',
    'region_name' => 'Hungary',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect',
    'shipping' => ',1,2,3',
    'code' => '36',
    'state' => '',
  ),
  119 => 
  array (
    'region_id' => '119',
    'region_code' => 'IS',
    'region_name' => 'Iceland',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect',
    'shipping' => ',1,3',
    'code' => '354',
    'state' => '',
  ),
  21 => 
  array (
    'region_id' => '21',
    'region_code' => 'IN',
    'region_name' => 'India',
    'payment' => ',PayPal,WiredTransfer,WesternUnion,CreditCard',
    'shipping' => ',1,2,3',
    'code' => '91',
    'state' => '',
  ),
  22 => 
  array (
    'region_id' => '22',
    'region_code' => 'ID',
    'region_name' => 'Indonesia',
    'payment' => ',PayPal,WiredTransfer,WesternUnion,CreditCard',
    'shipping' => ',1,3,2',
    'code' => '62',
    'state' => '',
  ),
  120 => 
  array (
    'region_id' => '120',
    'region_code' => 'IR',
    'region_name' => 'Iran, Islamic Republic of',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard',
    'shipping' => ',1,2',
    'code' => '98',
    'state' => '',
  ),
  307 => 
  array (
    'region_id' => '307',
    'region_code' => 'IQ',
    'region_name' => 'Iraq',
    'payment' => ',PayPal,WiredTransfer,WesternUnion,CreditCard',
    'shipping' => ',1,3',
    'code' => '964',
    'state' => '',
  ),
  229 => 
  array (
    'region_id' => '229',
    'region_code' => 'IE',
    'region_name' => 'Ireland',
    'payment' => ',PayPal,CreditCard,WesternUnion,WiredTransfer,webcollect',
    'shipping' => ',1,2,3',
    'code' => '353',
    'state' => '',
  ),
  308 => 
  array (
    'region_id' => '308',
    'region_code' => 'IM',
    'region_name' => 'Isle of Man',
    'payment' => ',PayPal,WiredTransfer,WesternUnion,CreditCard,webcollect,webcollect',
    'shipping' => ',1,2,3',
    'code' => '',
    'state' => '',
  ),
  230 => 
  array (
    'region_id' => '230',
    'region_code' => 'IL',
    'region_name' => 'Israel',
    'payment' => ',PayPal,CreditCard,WesternUnion,WiredTransfer,webcollect',
    'shipping' => ',1,2,3',
    'code' => '972',
    'state' => '',
  ),
  23 => 
  array (
    'region_id' => '23',
    'region_code' => 'IT',
    'region_name' => 'Italy',
    'payment' => ',PayPal,WiredTransfer,WesternUnion,CreditCard,webcollect',
    'shipping' => ',1,2,3',
    'code' => '39',
    'state' => '',
  ),
  123 => 
  array (
    'region_id' => '123',
    'region_code' => 'JM',
    'region_name' => 'Jamaica',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect',
    'shipping' => ',1,3',
    'code' => '1876',
    'state' => '',
  ),
  24 => 
  array (
    'region_id' => '24',
    'region_code' => 'JP',
    'region_name' => 'Japan',
    'payment' => ',PayPal,WiredTransfer,WesternUnion,CreditCard,webcollect',
    'shipping' => ',1,2,3',
    'code' => '81',
    'state' => '',
  ),
  310 => 
  array (
    'region_id' => '310',
    'region_code' => 'JE',
    'region_name' => 'Jersey',
    'payment' => ',PayPal,WiredTransfer,WesternUnion,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '44',
    'state' => '',
  ),
  125 => 
  array (
    'region_id' => '125',
    'region_code' => 'JO',
    'region_name' => 'Jordan',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,2,3',
    'code' => '962',
    'state' => '',
  ),
  126 => 
  array (
    'region_id' => '126',
    'region_code' => 'KZ',
    'region_name' => 'Kazakhstan',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,2,3',
    'code' => '7',
    'state' => '',
  ),
  127 => 
  array (
    'region_id' => '127',
    'region_code' => 'KE',
    'region_name' => 'Kenya',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,2,3',
    'code' => '254',
    'state' => '',
  ),
  311 => 
  array (
    'region_id' => '311',
    'region_code' => 'KI',
    'region_name' => 'Kiribati',
    'payment' => ',PayPal,WiredTransfer,WesternUnion,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '686',
    'state' => '',
  ),
  235 => 
  array (
    'region_id' => '235',
    'region_code' => 'KR',
    'region_name' => 'Korea',
    'payment' => ',PayPal,CreditCard,WesternUnion,WiredTransfer,webcollect,webcollect',
    'shipping' => ',1,3,2',
    'code' => '82',
    'state' => '',
  ),
  309 => 
  array (
    'region_id' => '309',
    'region_code' => 'KW',
    'region_name' => 'Kuwait',
    'payment' => ',PayPal,WiredTransfer,WesternUnion,CreditCard,webcollect,webcollect',
    'shipping' => ',1,2,3',
    'code' => '965',
    'state' => '',
  ),
  129 => 
  array (
    'region_id' => '129',
    'region_code' => 'KG',
    'region_name' => 'Kyrgyzstan',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,webcollect,webcollect,CreditCard',
    'shipping' => ',1',
    'code' => '996',
    'state' => '',
  ),
  130 => 
  array (
    'region_id' => '130',
    'region_code' => 'LA',
    'region_name' => 'Lao People\'s Democratic Republic',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,2,3',
    'code' => '856',
    'state' => '',
  ),
  131 => 
  array (
    'region_id' => '131',
    'region_code' => 'LV',
    'region_name' => 'Latvia',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,2,3',
    'code' => '371',
    'state' => '',
  ),
  132 => 
  array (
    'region_id' => '132',
    'region_code' => 'LB',
    'region_name' => 'Lebanon',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '961',
    'state' => '',
  ),
  133 => 
  array (
    'region_id' => '133',
    'region_code' => 'LS',
    'region_name' => 'Lesotho',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '266',
    'state' => '',
  ),
  134 => 
  array (
    'region_id' => '134',
    'region_code' => 'LR',
    'region_name' => 'Liberia',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '231',
    'state' => '',
  ),
  135 => 
  array (
    'region_id' => '135',
    'region_code' => 'LY',
    'region_name' => 'Libya',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '218',
    'state' => '',
  ),
  231 => 
  array (
    'region_id' => '231',
    'region_code' => 'LI',
    'region_name' => 'Liechtenstein',
    'payment' => ',PayPal,CreditCard,WesternUnion,WiredTransfer,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '423',
    'state' => '',
  ),
  136 => 
  array (
    'region_id' => '136',
    'region_code' => 'LT',
    'region_name' => 'Lithuania',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '370',
    'state' => '',
  ),
  137 => 
  array (
    'region_id' => '137',
    'region_code' => 'LU',
    'region_name' => 'Luxembourg',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,2,3',
    'code' => '352',
    'state' => '',
  ),
  304 => 
  array (
    'region_id' => '304',
    'region_code' => 'MO',
    'region_name' => 'Macao',
    'payment' => ',PayPal,WiredTransfer,WesternUnion,CreditCard,webcollect,webcollect',
    'shipping' => ',1,2,3',
    'code' => '853',
    'state' => '',
  ),
  138 => 
  array (
    'region_id' => '138',
    'region_code' => 'MK',
    'region_name' => 'Macedonia, The Former Yugoslav Republic Of',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '389',
    'state' => '',
  ),
  139 => 
  array (
    'region_id' => '139',
    'region_code' => 'MG',
    'region_name' => 'Madagascar',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,2,3',
    'code' => '261',
    'state' => '',
  ),
  140 => 
  array (
    'region_id' => '140',
    'region_code' => 'MW',
    'region_name' => 'Malawi',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '265',
    'state' => '',
  ),
  25 => 
  array (
    'region_id' => '25',
    'region_code' => 'MY',
    'region_name' => 'Malaysia',
    'payment' => ',PayPal,WiredTransfer,WesternUnion,CreditCard,webcollect,webcollect',
    'shipping' => ',1,2,3',
    'code' => '60',
    'state' => '',
  ),
  141 => 
  array (
    'region_id' => '141',
    'region_code' => 'MV',
    'region_name' => 'Maldives',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '960',
    'state' => '',
  ),
  142 => 
  array (
    'region_id' => '142',
    'region_code' => 'ML',
    'region_name' => 'Mali',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,2,3',
    'code' => '223',
    'state' => '',
  ),
  143 => 
  array (
    'region_id' => '143',
    'region_code' => 'MT',
    'region_name' => 'Malta',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect',
    'shipping' => ',1,2,3',
    'code' => '356',
    'state' => '',
  ),
  300 => 
  array (
    'region_id' => '300',
    'region_code' => 'MH',
    'region_name' => 'MARSHALL ISLANDS',
    'payment' => ',PayPal,WiredTransfer,WesternUnion,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '692',
    'state' => '',
  ),
  145 => 
  array (
    'region_id' => '145',
    'region_code' => 'MQ',
    'region_name' => 'MARTINIQUE',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '596',
    'state' => '',
  ),
  146 => 
  array (
    'region_id' => '146',
    'region_code' => 'MR',
    'region_name' => 'Mauritania',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '222',
    'state' => '',
  ),
  147 => 
  array (
    'region_id' => '147',
    'region_code' => 'MU',
    'region_name' => 'Mauritius',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '230',
    'state' => '',
  ),
  299 => 
  array (
    'region_id' => '299',
    'region_code' => 'YT',
    'region_name' => 'MAYOTTE',
    'payment' => ',PayPal,WiredTransfer,WesternUnion,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '262',
    'state' => '',
  ),
  26 => 
  array (
    'region_id' => '26',
    'region_code' => 'MX',
    'region_name' => 'Mexico',
    'payment' => ',PayPal,WiredTransfer,WesternUnion,CreditCard,webcollect,webcollect',
    'shipping' => ',1,2,3',
    'code' => '52',
    'state' => '',
  ),
  298 => 
  array (
    'region_id' => '298',
    'region_code' => 'FM',
    'region_name' => 'Micronesia, Federated States Of',
    'payment' => ',PayPal,WiredTransfer,WesternUnion,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '691',
    'state' => '',
  ),
  148 => 
  array (
    'region_id' => '148',
    'region_code' => 'MD',
    'region_name' => 'Moldova, Republic Of',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,webcollect,webcollect,CreditCard',
    'shipping' => ',1,3',
    'code' => '373',
    'state' => '',
  ),
  27 => 
  array (
    'region_id' => '27',
    'region_code' => 'MC',
    'region_name' => 'Monaco',
    'payment' => ',PayPal,WiredTransfer,WesternUnion,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '377',
    'state' => '',
  ),
  297 => 
  array (
    'region_id' => '297',
    'region_code' => 'MN',
    'region_name' => 'Mongolia',
    'payment' => ',PayPal,WiredTransfer,WesternUnion,CreditCard,webcollect,webcollect',
    'shipping' => ',1,2,3',
    'code' => '976',
    'state' => '',
  ),
  236 => 
  array (
    'region_id' => '236',
    'region_code' => 'ME',
    'region_name' => 'Montenegro',
    'payment' => ',PayPal,CreditCard,WesternUnion,WiredTransfer,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '382',
    'state' => '',
  ),
  149 => 
  array (
    'region_id' => '149',
    'region_code' => 'MS',
    'region_name' => 'Montserrat',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '1664',
    'state' => '',
  ),
  150 => 
  array (
    'region_id' => '150',
    'region_code' => 'MA',
    'region_name' => 'Morocco',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect',
    'shipping' => ',1,2,3',
    'code' => '212',
    'state' => '',
  ),
  151 => 
  array (
    'region_id' => '151',
    'region_code' => 'MZ',
    'region_name' => 'Mozambique',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,2,3',
    'code' => '258',
    'state' => '',
  ),
  293 => 
  array (
    'region_id' => '293',
    'region_code' => 'MM',
    'region_name' => 'Myanmar',
    'payment' => ',PayPal,WiredTransfer,WesternUnion,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '95',
    'state' => '',
  ),
  152 => 
  array (
    'region_id' => '152',
    'region_code' => 'NA',
    'region_name' => 'Namibia',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '264',
    'state' => '',
  ),
  153 => 
  array (
    'region_id' => '153',
    'region_code' => 'NR',
    'region_name' => 'Nauru',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '674',
    'state' => '',
  ),
  154 => 
  array (
    'region_id' => '154',
    'region_code' => 'NP',
    'region_name' => 'Nepal',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,2,3',
    'code' => '977',
    'state' => '',
  ),
  28 => 
  array (
    'region_id' => '28',
    'region_code' => 'NL',
    'region_name' => 'Netherlands',
    'payment' => ',PayPal,WiredTransfer,WesternUnion,CreditCard,webcollect',
    'shipping' => ',1,3',
    'code' => '31',
    'state' => '',
  ),
  92 => 
  array (
    'region_id' => '92',
    'region_code' => 'AN',
    'region_name' => 'Netherlands Antilles',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '599',
    'state' => '',
  ),
  290 => 
  array (
    'region_id' => '290',
    'region_code' => 'NC',
    'region_name' => 'New Caledonia',
    'payment' => ',PayPal,WiredTransfer,WesternUnion,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '687',
    'state' => '',
  ),
  29 => 
  array (
    'region_id' => '29',
    'region_code' => 'NZ',
    'region_name' => 'New Zealand',
    'payment' => ',PayPal,WiredTransfer,WesternUnion,CreditCard,webcollect',
    'shipping' => ',1,2,3',
    'code' => '64',
    'state' => '',
  ),
  155 => 
  array (
    'region_id' => '155',
    'region_code' => 'NI',
    'region_name' => 'Nicaragua',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '505',
    'state' => '',
  ),
  156 => 
  array (
    'region_id' => '156',
    'region_code' => 'NE',
    'region_name' => 'Niger',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,2,3',
    'code' => '227',
    'state' => '',
  ),
  157 => 
  array (
    'region_id' => '157',
    'region_code' => 'NG',
    'region_name' => 'Nigeria',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard',
    'shipping' => ',1,2,3',
    'code' => '234',
    'state' => '',
  ),
  289 => 
  array (
    'region_id' => '289',
    'region_code' => 'NU',
    'region_name' => 'Niue',
    'payment' => ',PayPal,WiredTransfer,WesternUnion,CreditCard,webcollect',
    'shipping' => ',1,3',
    'code' => '683',
    'state' => '',
  ),
  288 => 
  array (
    'region_id' => '288',
    'region_code' => 'NF',
    'region_name' => 'Norfolk Island',
    'payment' => ',PayPal,WiredTransfer,WesternUnion,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '672',
    'state' => '',
  ),
  287 => 
  array (
    'region_id' => '287',
    'region_code' => 'MP',
    'region_name' => 'Northern Mariana Islands',
    'payment' => ',PayPal,WiredTransfer,WesternUnion,CreditCard,webcollect,webcollect',
    'shipping' => ',1,2,3',
    'code' => '1670',
    'state' => '',
  ),
  30 => 
  array (
    'region_id' => '30',
    'region_code' => 'NO',
    'region_name' => 'Norway',
    'payment' => ',PayPal,WiredTransfer,WesternUnion,CreditCard,webcollect',
    'shipping' => ',1,2,3',
    'code' => '47',
    'state' => '',
  ),
  158 => 
  array (
    'region_id' => '158',
    'region_code' => 'OM',
    'region_name' => 'Oman',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect',
    'shipping' => ',1,2,3',
    'code' => '968',
    'state' => '',
  ),
  316 => 
  array (
    'region_id' => '316',
    'region_code' => 'OO',
    'region_name' => 'Other',
    'payment' => ',PayPal,WesternUnion,WiredTransfer,webcollect,webcollect,CreditCard',
    'shipping' => ',1',
    'code' => '',
    'state' => '',
  ),
  314 => 
  array (
    'region_id' => '314',
    'region_code' => 'PK',
    'region_name' => 'Pakistan',
    'payment' => ',PayPal,WiredTransfer,WesternUnion,CreditCard',
    'shipping' => ',1,2,3',
    'code' => '92',
    'state' => '',
  ),
  285 => 
  array (
    'region_id' => '285',
    'region_code' => 'PW',
    'region_name' => 'Palau',
    'payment' => ',PayPal,WiredTransfer,WesternUnion,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '680',
    'state' => '',
  ),
  159 => 
  array (
    'region_id' => '159',
    'region_code' => 'PA',
    'region_name' => 'Panama',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,2,3',
    'code' => '507',
    'state' => '',
  ),
  315 => 
  array (
    'region_id' => '315',
    'region_code' => 'PG',
    'region_name' => 'Papua New Guinea',
    'payment' => ',PayPal,WiredTransfer,WesternUnion,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3,2',
    'code' => '675',
    'state' => '',
  ),
  160 => 
  array (
    'region_id' => '160',
    'region_code' => 'PY',
    'region_name' => 'Paraguay',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '595',
    'state' => '',
  ),
  232 => 
  array (
    'region_id' => '232',
    'region_code' => 'PE',
    'region_name' => 'Peru',
    'payment' => ',PayPal,WesternUnion,CreditCard,WiredTransfer,webcollect,webcollect',
    'shipping' => ',1,3,2',
    'code' => '51',
    'state' => '',
  ),
  283 => 
  array (
    'region_id' => '283',
    'region_code' => 'PH',
    'region_name' => 'Philippines',
    'payment' => ',PayPal,WiredTransfer,WesternUnion,CreditCard',
    'shipping' => ',1,2,3',
    'code' => '63',
    'state' => '',
  ),
  282 => 
  array (
    'region_id' => '282',
    'region_code' => 'PN',
    'region_name' => 'Pitcairn',
    'payment' => ',PayPal,WiredTransfer,WesternUnion,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '64',
    'state' => '',
  ),
  161 => 
  array (
    'region_id' => '161',
    'region_code' => 'PL',
    'region_name' => 'Poland',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,2,3',
    'code' => '48',
    'state' => '',
  ),
  31 => 
  array (
    'region_id' => '31',
    'region_code' => 'PT',
    'region_name' => 'Portugal',
    'payment' => ',PayPal,WiredTransfer,WesternUnion,CreditCard,webcollect,webcollect',
    'shipping' => ',1,2,3',
    'code' => '351',
    'state' => '',
  ),
  163 => 
  array (
    'region_id' => '163',
    'region_code' => 'PR',
    'region_name' => 'Puerto Rico',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect',
    'shipping' => ',1,3',
    'code' => '1787',
    'state' => '',
  ),
  165 => 
  array (
    'region_id' => '165',
    'region_code' => 'QA',
    'region_name' => 'Qatar',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,2,3',
    'code' => '974',
    'state' => '',
  ),
  164 => 
  array (
    'region_id' => '164',
    'region_code' => 'RE',
    'region_name' => 'Reunion',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '262',
    'state' => '',
  ),
  167 => 
  array (
    'region_id' => '167',
    'region_code' => 'RO',
    'region_name' => 'Romania',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,2,3',
    'code' => '40',
    'state' => '',
  ),
  32 => 
  array (
    'region_id' => '32',
    'region_code' => 'RU',
    'region_name' => 'Russian Federation',
    'payment' => ',PayPal,WiredTransfer,WesternUnion,CreditCard,webmoney',
    'shipping' => ',1,2',
    'code' => '7',
    'state' => '',
  ),
  168 => 
  array (
    'region_id' => '168',
    'region_code' => 'RW',
    'region_name' => 'Rwanda',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,2,3',
    'code' => '250',
    'state' => '',
  ),
  280 => 
  array (
    'region_id' => '280',
    'region_code' => 'BL',
    'region_name' => 'Saint Barthelemy',
    'payment' => ',PayPal,WiredTransfer,WesternUnion,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '',
    'state' => '',
  ),
  279 => 
  array (
    'region_id' => '279',
    'region_code' => 'SH',
    'region_name' => 'Saint Helena, Ascension and Tristan da Cunha',
    'payment' => ',PayPal,WiredTransfer,WesternUnion,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '290',
    'state' => '',
  ),
  274 => 
  array (
    'region_id' => '274',
    'region_code' => 'KN',
    'region_name' => 'Saint Kitts and Nevis',
    'payment' => ',PayPal,WiredTransfer,WesternUnion,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '1869',
    'state' => '',
  ),
  270 => 
  array (
    'region_id' => '270',
    'region_code' => 'LC',
    'region_name' => 'Saint Lucia',
    'payment' => ',PayPal,WiredTransfer,WesternUnion,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '1758',
    'state' => '',
  ),
  268 => 
  array (
    'region_id' => '268',
    'region_code' => 'MF',
    'region_name' => 'Saint Martin',
    'payment' => ',PayPal,WiredTransfer,WesternUnion,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '',
    'state' => '',
  ),
  267 => 
  array (
    'region_id' => '267',
    'region_code' => 'PM',
    'region_name' => 'Saint Pierre and Miquelon',
    'payment' => ',PayPal,WiredTransfer,WesternUnion,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '508',
    'state' => '',
  ),
  266 => 
  array (
    'region_id' => '266',
    'region_code' => 'VC',
    'region_name' => 'Saint Vincent and the Grenadines',
    'payment' => ',PayPal,WiredTransfer,WesternUnion,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '1784',
    'state' => '',
  ),
  318 => 
  array (
    'region_id' => '318',
    'region_code' => 'MP',
    'region_name' => 'Saipan',
    'payment' => ',PayPal,webcollect,CreditCard,WesternUnion,WiredTransfer',
    'shipping' => ',1,3',
    'code' => '1670',
    'state' => '',
  ),
  265 => 
  array (
    'region_id' => '265',
    'region_code' => 'WS',
    'region_name' => 'Samoa',
    'payment' => ',PayPal,WiredTransfer,WesternUnion,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '685',
    'state' => '',
  ),
  264 => 
  array (
    'region_id' => '264',
    'region_code' => 'SM',
    'region_name' => 'San Marino',
    'payment' => ',PayPal,WiredTransfer,WesternUnion,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '378',
    'state' => '',
  ),
  171 => 
  array (
    'region_id' => '171',
    'region_code' => 'ST',
    'region_name' => 'Sao Tome and Principe',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '239',
    'state' => '',
  ),
  172 => 
  array (
    'region_id' => '172',
    'region_code' => 'SA',
    'region_name' => 'Saudi Arabia',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard',
    'shipping' => ',1,3,2',
    'code' => '966',
    'state' => '',
  ),
  173 => 
  array (
    'region_id' => '173',
    'region_code' => 'SN',
    'region_name' => 'Senegal',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,2,3',
    'code' => '221',
    'state' => '',
  ),
  174 => 
  array (
    'region_id' => '174',
    'region_code' => 'RS',
    'region_name' => 'Serbia',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '381',
    'state' => '',
  ),
  175 => 
  array (
    'region_id' => '175',
    'region_code' => 'SC',
    'region_name' => 'Seychelles',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '248',
    'state' => '',
  ),
  263 => 
  array (
    'region_id' => '263',
    'region_code' => 'SL',
    'region_name' => 'Sierra Leone',
    'payment' => ',PayPal,WiredTransfer,WesternUnion,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '232',
    'state' => '',
  ),
  238 => 
  array (
    'region_id' => '238',
    'region_code' => 'SG',
    'region_name' => 'Singapore',
    'payment' => ',PayPal,CreditCard,WesternUnion,WiredTransfer',
    'shipping' => ',1,2,3',
    'code' => '65',
    'state' => '',
  ),
  262 => 
  array (
    'region_id' => '262',
    'region_code' => 'SX',
    'region_name' => 'Sint Maarten (Dutch Part)',
    'payment' => ',PayPal,WiredTransfer,WesternUnion,CreditCard,webcollect,webcollect',
    'shipping' => ',1,2,3',
    'code' => '',
    'state' => '',
  ),
  176 => 
  array (
    'region_id' => '176',
    'region_code' => 'SK',
    'region_name' => 'Slovakia',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '421',
    'state' => '',
  ),
  177 => 
  array (
    'region_id' => '177',
    'region_code' => 'SI',
    'region_name' => 'Slovenia',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '386',
    'state' => '',
  ),
  179 => 
  array (
    'region_id' => '179',
    'region_code' => 'SO',
    'region_name' => 'Somalia',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '252',
    'state' => '',
  ),
  233 => 
  array (
    'region_id' => '233',
    'region_code' => 'ZA',
    'region_name' => 'South Africa',
    'payment' => ',PayPal,CreditCard,WesternUnion,WiredTransfer',
    'shipping' => ',1,3',
    'code' => '27',
    'state' => '',
  ),
  261 => 
  array (
    'region_id' => '261',
    'region_code' => 'GS',
    'region_name' => 'South Georgia and the South Sandwich Islands',
    'payment' => ',PayPal,WiredTransfer,WesternUnion,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '',
    'state' => '',
  ),
  312 => 
  array (
    'region_id' => '312',
    'region_code' => 'KR',
    'region_name' => 'South Korea',
    'payment' => ',PayPal,WiredTransfer,WesternUnion,CreditCard,webcollect,webcollect',
    'shipping' => ',1,2,3',
    'code' => '82',
    'state' => '',
  ),
  33 => 
  array (
    'region_id' => '33',
    'region_code' => 'ES',
    'region_name' => 'Spain',
    'payment' => ',PayPal,WiredTransfer,WesternUnion,CreditCard,webcollect,webcollect,DirectDebit,BankTransfer',
    'shipping' => ',1,2,3',
    'code' => '34',
    'state' => 
    array (
      0 => 'A Corua',
      1 => 'Alava',
      2 => 'Albacete',
      3 => 'Alicante',
      4 => 'Almeria',
      5 => 'Asturias',
      6 => 'Avila',
      7 => 'Badajoz',
      8 => 'Baleares',
      9 => 'Barcelona',
      10 => 'Burgos',
      11 => 'Caceres',
      12 => 'Cadiz',
      13 => 'Cantabria',
      14 => 'Castellon',
      15 => 'Ceuta',
      16 => 'Ciudad Real',
      17 => 'Cordoba',
      18 => 'Cuenca',
      19 => 'Girona',
      20 => 'Granada',
      21 => 'Guadalajara',
      22 => 'Guipuzcoa',
      23 => 'Huelva',
      24 => 'Huesca',
      25 => 'Jaen',
      26 => 'La Coruna',
      27 => 'La Rioja',
      28 => 'Las Palmas',
      29 => 'Leon',
      30 => 'Lleida',
      31 => 'Lugo',
      32 => 'Madrid',
      33 => 'Malaga',
      34 => 'Melilla',
      35 => 'Murcia',
      36 => 'Navarra',
      37 => 'Ourense',
      38 => 'Palencia',
      39 => 'Pontevedra',
      40 => 'Salamanca',
      41 => 'Santa Cruz de Tenerife',
      42 => 'Segovia',
      43 => 'Sevilla',
      44 => 'Soria',
      45 => 'Tarragona',
      46 => 'Teruel',
      47 => 'Toledo',
      48 => 'Valencia',
      49 => 'Valladolid',
      50 => 'Vizcaya',
      51 => 'Zamora',
      52 => 'Zaragoza',
    ),
  ),
  180 => 
  array (
    'region_id' => '180',
    'region_code' => 'LK',
    'region_name' => 'Sri Lanka',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,2,3',
    'code' => '94',
    'state' => '',
  ),
  190 => 
  array (
    'region_id' => '190',
    'region_code' => 'SD',
    'region_name' => 'Sudan',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '249',
    'state' => '',
  ),
  191 => 
  array (
    'region_id' => '191',
    'region_code' => 'SR',
    'region_name' => 'Suriname',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '597',
    'state' => '',
  ),
  260 => 
  array (
    'region_id' => '260',
    'region_code' => 'SJ',
    'region_name' => 'Svalbard and Jan Mayen',
    'payment' => ',PayPal,WiredTransfer,WesternUnion,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '47',
    'state' => '',
  ),
  192 => 
  array (
    'region_id' => '192',
    'region_code' => 'SZ',
    'region_name' => 'Swaziland',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect',
    'shipping' => ',1,3',
    'code' => '268',
    'state' => '',
  ),
  34 => 
  array (
    'region_id' => '34',
    'region_code' => 'SE',
    'region_name' => 'Sweden',
    'payment' => ',PayPal,WiredTransfer,WesternUnion,CreditCard,webcollect',
    'shipping' => ',1,2,3',
    'code' => '46',
    'state' => '',
  ),
  35 => 
  array (
    'region_id' => '35',
    'region_code' => 'CH',
    'region_name' => 'Switzerland',
    'payment' => ',WiredTransfer,WesternUnion,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,2,3',
    'code' => '41',
    'state' => 
    array (
      0 => 'Aargau',
      1 => 'Appenzell Ausserrhoden',
      2 => 'Appenzell Innerrhoden',
      3 => 'Basel-Landschaft',
      4 => 'Basel-Stadt',
      5 => 'Bern',
      6 => 'Freiburg',
      7 => 'Genf',
      8 => 'Glarus',
      9 => 'Graubnden',
      10 => 'Jura',
      11 => 'Luzern',
      12 => 'Neuenburg',
      13 => 'Nidwalden',
      14 => 'Obwalden',
      15 => 'Schaffhausen',
      16 => 'Schwyz',
      17 => 'Solothurn',
      18 => 'St. Gallen',
      19 => 'Tessin',
      20 => 'Thurgau',
      21 => 'Uri',
      22 => 'Waadt',
      23 => 'Wallis',
      24 => 'Zrich',
      25 => 'Zug',
    ),
  ),
  259 => 
  array (
    'region_id' => '259',
    'region_code' => 'SY',
    'region_name' => 'Syrian Arab Republic',
    'payment' => ',PayPal,WiredTransfer,WesternUnion,CreditCard,webcollect,webcollect',
    'shipping' => ',1,2,3',
    'code' => '963',
    'state' => '',
  ),
  197 => 
  array (
    'region_id' => '197',
    'region_code' => 'TJ',
    'region_name' => 'Tajikistan',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1',
    'code' => '992',
    'state' => '',
  ),
  258 => 
  array (
    'region_id' => '258',
    'region_code' => 'TZ',
    'region_name' => 'Tanzania, United Republic of',
    'payment' => ',PayPal,WiredTransfer,WesternUnion,CreditCard',
    'shipping' => ',1,3',
    'code' => '255',
    'state' => '',
  ),
  36 => 
  array (
    'region_id' => '36',
    'region_code' => 'TH',
    'region_name' => 'Thailand',
    'payment' => ',WiredTransfer,WesternUnion,PayPal,CreditCard',
    'shipping' => ',1,2,3',
    'code' => '66',
    'state' => '',
  ),
  199 => 
  array (
    'region_id' => '199',
    'region_code' => 'TG',
    'region_name' => 'Togo',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '228',
    'state' => '',
  ),
  257 => 
  array (
    'region_id' => '257',
    'region_code' => 'TK',
    'region_name' => 'Tokelau',
    'payment' => ',PayPal,WiredTransfer,WesternUnion,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '690',
    'state' => '',
  ),
  200 => 
  array (
    'region_id' => '200',
    'region_code' => 'TO',
    'region_name' => 'Tonga',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '676',
    'state' => '',
  ),
  201 => 
  array (
    'region_id' => '201',
    'region_code' => 'TT',
    'region_name' => 'Trinidad and Tobago',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '1868',
    'state' => '',
  ),
  202 => 
  array (
    'region_id' => '202',
    'region_code' => 'TN',
    'region_name' => 'Tunisia',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect',
    'shipping' => ',1,2,3',
    'code' => '216',
    'state' => '',
  ),
  203 => 
  array (
    'region_id' => '203',
    'region_code' => 'TR',
    'region_name' => 'Turkey',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,2,3',
    'code' => '90',
    'state' => '',
  ),
  204 => 
  array (
    'region_id' => '204',
    'region_code' => 'TM',
    'region_name' => 'Turkmenistan',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '993',
    'state' => '',
  ),
  255 => 
  array (
    'region_id' => '255',
    'region_code' => 'TC',
    'region_name' => 'Turks and Caicos Islands',
    'payment' => ',PayPal,WiredTransfer,WesternUnion,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '1649',
    'state' => '',
  ),
  207 => 
  array (
    'region_id' => '207',
    'region_code' => 'TV',
    'region_name' => 'Tuvalu',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '688',
    'state' => '',
  ),
  209 => 
  array (
    'region_id' => '209',
    'region_code' => 'UG',
    'region_name' => 'Uganda',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,2,3',
    'code' => '256',
    'state' => '',
  ),
  37 => 
  array (
    'region_id' => '37',
    'region_code' => 'UA',
    'region_name' => 'Ukraine',
    'payment' => ',WiredTransfer,WesternUnion,PayPal,CreditCard',
    'shipping' => ',1,2',
    'code' => '380',
    'state' => '',
  ),
  251 => 
  array (
    'region_id' => '251',
    'region_code' => 'AE',
    'region_name' => 'United Arab Emirates',
    'payment' => ',PayPal,WiredTransfer,WesternUnion,CreditCard,webcollect,webcollect',
    'shipping' => ',1,2,3',
    'code' => '971',
    'state' => '',
  ),
  40 => 
  array (
    'region_id' => '40',
    'region_code' => 'GB',
    'region_name' => 'United Kingdom',
    'payment' => ',WiredTransfer,WesternUnion,PayPal,CreditCard',
    'shipping' => ',1,2,3',
    'code' => '44',
    'state' => '',
  ),
  41 => 
  array (
    'region_id' => '41',
    'region_code' => 'US',
    'region_name' => 'United States',
    'payment' => ',WiredTransfer,WesternUnion,CreditCard,PayPal',
    'shipping' => ',1,2,3',
    'code' => '1',
    'state' => 
    array (
      0 => 'Alabama',
      1 => 'Alaska',
      2 => 'Arizona',
      3 => 'Arkansas',
      4 => 'Armed Forces Africa',
      5 => 'Armed Forces Americas',
      6 => 'Armed Forces Canada',
      7 => 'Armed Forces Europe',
      8 => 'Armed Forces Middle East',
      9 => 'Armed Forces Pacific',
      10 => 'California',
      11 => 'Colorado',
      12 => 'Connecticut',
      13 => 'Delaware',
      14 => 'District of Columbia',
      15 => 'Florida',
      16 => 'Georgia',
      17 => 'Hawaii',
      18 => 'Idaho',
      19 => 'Illinois',
      20 => 'Indiana',
      21 => 'Iowa',
      22 => 'Kansas',
      23 => 'Kentucky',
      24 => 'Louisiana',
      25 => 'Maine',
      26 => 'Maryland',
      27 => 'Massachusetts',
      28 => 'Michigan',
      29 => 'Minnesota',
      30 => 'Mississippi',
      31 => 'Missouri',
      32 => 'Montana',
      33 => 'Nebraska',
      34 => 'Nevada',
      35 => 'New Hampshire',
      36 => 'New Jersey',
      37 => 'New Mexico',
      38 => 'New York',
      39 => 'North Carolina',
      40 => 'North Dakota',
      41 => 'Ohio',
      42 => 'Oklahoma',
      43 => 'Oregon',
      44 => 'Pennsylvania',
      45 => 'Rhode Island',
      46 => 'South Carolina',
      47 => 'South Dakota',
      48 => 'Tennessee',
      49 => 'Texas',
      50 => 'Utah',
      51 => 'Vermont',
      52 => 'Virginia',
      53 => 'Washington',
      54 => 'West Virginia',
      55 => 'Wisconsin',
      56 => 'Wyoming',
    ),
  ),
  250 => 
  array (
    'region_id' => '250',
    'region_code' => 'UM',
    'region_name' => 'United States Minor Outlying Islands',
    'payment' => ',PayPal,WiredTransfer,WesternUnion,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '',
    'state' => '',
  ),
  211 => 
  array (
    'region_id' => '211',
    'region_code' => 'UY',
    'region_name' => 'Uruguay',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '598',
    'state' => '',
  ),
  214 => 
  array (
    'region_id' => '214',
    'region_code' => 'UZ',
    'region_name' => 'Uzbekistan',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1',
    'code' => '998',
    'state' => '',
  ),
  215 => 
  array (
    'region_id' => '215',
    'region_code' => 'VU',
    'region_name' => 'Vanuatu',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '678',
    'state' => '',
  ),
  248 => 
  array (
    'region_id' => '248',
    'region_code' => 'VE',
    'region_name' => 'Venezuela, Bolvarian Republic of',
    'payment' => ',PayPal,WiredTransfer,WesternUnion,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '58',
    'state' => '',
  ),
  247 => 
  array (
    'region_id' => '247',
    'region_code' => 'VN',
    'region_name' => 'Viet Nam',
    'payment' => ',PayPal,WiredTransfer,WesternUnion,CreditCard',
    'shipping' => ',1,2,3',
    'code' => '84',
    'state' => '',
  ),
  246 => 
  array (
    'region_id' => '246',
    'region_code' => 'VG',
    'region_name' => 'Virgin Islands, British',
    'payment' => ',PayPal,WiredTransfer,WesternUnion,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '1284',
    'state' => '',
  ),
  217 => 
  array (
    'region_id' => '217',
    'region_code' => 'VI',
    'region_name' => 'Virgin Islands, U.S.',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '1340',
    'state' => '',
  ),
  243 => 
  array (
    'region_id' => '243',
    'region_code' => 'WF',
    'region_name' => 'Wallis and Futuna',
    'payment' => ',PayPal,WiredTransfer,WesternUnion,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '681',
    'state' => '',
  ),
  242 => 
  array (
    'region_id' => '242',
    'region_code' => 'EH',
    'region_name' => 'Western Sahara',
    'payment' => ',PayPal,WiredTransfer,WesternUnion,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '213',
    'state' => '',
  ),
  220 => 
  array (
    'region_id' => '220',
    'region_code' => 'YE',
    'region_name' => 'Yemen',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '967',
    'state' => '',
  ),
  221 => 
  array (
    'region_id' => '221',
    'region_code' => 'ZM',
    'region_name' => 'Zambia',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '260',
    'state' => '',
  ),
  222 => 
  array (
    'region_id' => '222',
    'region_code' => 'ZW',
    'region_name' => 'Zimbabwe',
    'payment' => ',WesternUnion,WiredTransfer,PayPal,CreditCard,webcollect,webcollect',
    'shipping' => ',1,3',
    'code' => '263',
    'state' => '',
  ),
);
?>