<?php
return array (
  'webtitle' => 'dealsmachine.com 管理中心',
  'shop_name' => 'dealsmachine',
  'email_shop_name' => 'dealsmachine.com',
  'shop_title' => 'Best Deals Online - Cool Gadgets and Electronics Deals',
  'shop_keywords' => 'wholesale electronics, china wholesale, china electronics, discount wholesale electronics, cheap wholesale electronics, china supplier,Android tablet pc, china trade, wholesale distributor, china dropshipper,android phone,tablet pc',
  'shop_desc' => 'dealsmachine.com offers cool gadgets and electronics at great prices, browse cell phones, tablet pcs, computers, gadgets and other electronics deals and save big!',
  'shop_country' => '1',
  'shop_province' => '2',
  'shop_city' => '52',
  'shop_address' => 'address',
  'msn' => 'msn001',
  'service_email' => 'server@dealsmachine.com',
  'service_phone' => '010-12341234',
  'shop_closed' => '0',
  'lang' => 'eng',
  'top10_time' => 0,
  'close_comment' => '',
  'price_grade' => '1.29|1.26|1.25|1.24',
  'shop_logo' => '',
  'licensed' => '0',
  'shop_reg_closed' => '0',
  'is_html_url' => 1,
  'icp_file' => '',
  'display' => 'list',
  'watermark' => 'waterfile/water.png',
  'watermark_place' => '0',
  'watermark_alpha' => 0.56,
  'use_storage' => '1',
  'market_price_rate' => 1.2,
  'integral_percent' => '1',
  'sn_prefix' => 'ELOAD',
  'comment_check' => '1',
  'no_picture' => '/temp/skin1/images/no_pic.jpg',
  'stats_code' => '',
  'cache_time' => 3600,
  'timezone' => '8',
  'upload_size_limit' => '64',
  'cron_method' => '0',
  'comment_factor' => '0',
  'enable_order_check' => '1',
  'default_storage' => 1,
  'visit_stats' => 'on',
  'send_mail_on' => 'off',
  'auto_generate_gallery' => '0',
  'retain_original_img' => '1',
  'member_email_validate' => '1',
  'message_board' => '1',
  'date_format' => 'Y-m-d',
  'time_format' => 'Y-m-d H:i:s',
  'AM_time_format' => 'd/m/Y H:i:s A',
  'currency_format' => '%s',
  'thumb_width' => 100,
  'thumb_height' => 100,
  'webgrid_width' => 150,
  'webgrid_height' => 150,
  'image_width' => 250,
  'image_height' => 250,
  'top_number' => 5,
  'history_number' => 9,
  'comments_number' => 5,
  'bought_goods' => 5,
  'article_number' => 10,
  'goods_name_length' => 35,
  'price_format' => '0',
  'page_size' => 20,
  'sort_order_type' => '0',
  'sort_order_method' => '0',
  'show_order_type' => 'l',
  'attr_related_number' => '5',
  'goods_gallery_number' => 5,
  'article_title_length' => '30',
  'name_of_region_1' => '国家',
  'search_keywords' => 'MP3,MP4,Bluetooth,1GB,2GB,4GB,P168,P168++,Car DVD,Flash Memory Drive,GPS,CECT',
  'related_goods_number' => '4',
  'help_open' => '1',
  'article_page_size' => '10',
  'page_style' => '1',
  'recommend_order' => '0',
  'can_invoice' => '1',
  'use_integral' => '1',
  'use_bonus' => '1',
  'use_surplus' => '1',
  'use_how_oos' => '1',
  'send_confirm_email' => '0',
  'send_ship_email' => '0',
  'send_cancel_email' => '0',
  'send_invalid_email' => '0',
  'order_pay_note' => '1',
  'order_unpay_note' => '1',
  'order_ship_note' => '1',
  'order_receive_note' => '1',
  'order_unship_note' => '1',
  'order_return_note' => '1',
  'order_invalid_note' => '1',
  'order_cancel_note' => '1',
  'anonymous_buy' => '1',
  'min_goods_amount' => 0,
  'one_step_buy' => 0,
  'stock_dec_time' => '0',
  'cart_confirm' => '3',
  'send_service_email' => '0',
  'show_goods_in_cart' => '3',
  'show_attr_in_cart' => '1',
  'smtp_host' => 'k2smtpout.secureserver.net.',
  'smtp_port' => '25',
  'smtp_user' => 'server',
  'smtp_pass' => 'e6ta7996',
  'smtp_mail' => 'server@dealsmachine.com',
  'mail_charset' => 'UTF8',
  'mail_service' => '0',
  'smtp_ssl' => '0',
  'integrate_code' => 'eload',
  'integrate_config' => '',
  'hash_code' => 'c71d26cabebad7bce64c28bb6fea6770',
  'keys_code' => 'c71d26cabebad7bce64c28bb6fea6770',
  'template' => 'default',
  'install_date' => '1239871861',
  'eload_version' => 'v1.0',
  'sms_user_name' => '',
  'sms_password' => '',
  'most_searched_tags' => '',
  'sms_domain' => '',
  'sms_count' => '',
  'sms_total_money' => '',
  'sms_balance' => '',
  'sms_last_request' => '',
  'affiliate' => 'a:3:{s:6:"config";a:7:{s:6:"expire";d:24;s:11:"expire_unit";s:4:"hour";s:11:"separate_by";i:0;s:15:"level_point_all";s:2:"5%";s:15:"level_money_all";s:2:"1%";s:18:"level_register_all";i:2;s:17:"level_register_up";i:60;}s:4:"item";a:4:{i:0;a:2:{s:11:"level_point";s:3:"60%";s:11:"level_money";s:3:"60%";}i:1;a:2:{s:11:"level_point";s:3:"30%";s:11:"level_money";s:3:"30%";}i:2;a:2:{s:11:"level_point";s:2:"7%";s:11:"level_money";s:2:"7%";}i:3;a:2:{s:11:"level_point";s:2:"3%";s:11:"level_money";s:2:"3%";}}s:2:"on";i:1;}',
  'captcha' => '36',
  'captcha_width' => '100',
  'captcha_height' => '20',
  'sitemap' => 'a:6:{s:19:"homepage_changefreq";s:6:"hourly";s:17:"homepage_priority";s:3:"0.9";s:19:"category_changefreq";s:6:"hourly";s:17:"category_priority";s:3:"0.8";s:18:"content_changefreq";s:6:"weekly";s:16:"content_priority";s:3:"0.7";}',
  'points_rule' => '',
  'flash_theme' => 'dynfocus',
  'show_goodssn' => '1',
  'show_brand' => '1',
  'show_goodsweight' => '1',
  'show_goodsnumber' => '1',
  'show_addtime' => '1',
  'goodsattr_style' => '1',
  'show_marketprice' => '1',
  'sms_shop_mobile' => '',
  'sms_order_placed' => '0',
  'sms_order_payed' => '0',
  'sms_order_shipped' => '0',
  'wap_config' => '0',
  'wap_logo' => '',
  'message_check' => '1',
  'best_number' => 3,
  'new_number' => 3,
  'hot_number' => 3,
  'promote_number' => 3,
  'point_rate' => 0.02,
  'min_use_point' => 20,
  'l' =>
  array (
    'ln' => 'goods_name asc,sort_order',
    'lnd' => 'goods_name desc,sort_order',
    'lt' => 'is_hot desc,(select count(*) from `eload_order_goods` as o where o.goods_id = g.goods_id  AND  DATEDIFF(curdate(),FROM_UNIXTIME(o.addtime,\'%Y-%m-%d\')) <= 10 ) * g.shop_price desc,sort_order,click_count desc,goods_id desc ',
    'lp' => 'shop_price asc,sort_order',
    'lpd' => 'shop_price desc,sort_order',
    'ls' => 'goods_id desc,sort_order',
    'lh' => '(select sum(o.goods_number) * o.goods_price from `eload_order_goods` as o,eload_order_info AS oi where o.goods_id = g.goods_id and o.order_id = oi.order_id and oi.order_status > 0 and oi.order_status < 9 AND  DATEDIFF(curdate(),FROM_UNIXTIME(oi.add_time,\'%Y-%m-%d\')) <= 31 group by o.goods_id ) desc,sort_order,click_count desc,goods_id desc',
  ),
  'g' =>
  array (
    'gn' => 'goods_name asc,sort_order',
    'gnd' => 'goods_name desc,sort_order',
    'gt' => 'is_hot desc,( select count(*) from `eload_order_goods` as o where o.goods_id = g.goods_id  AND  DATEDIFF(curdate(),FROM_UNIXTIME(o.addtime,\'%Y-%m-%d\')) <= 10 ) * g.shop_price desc,sort_order,click_count desc,goods_id desc ',
    'gp' => 'shop_price asc,sort_order',
    'gpd' => 'shop_price desc,sort_order',
    'gs' => 'goods_id desc,sort_order',
    'gh' => '(select sum(o.goods_number) * o.goods_price from `eload_order_goods` as o,eload_order_info AS oi where o.goods_id = g.goods_id and o.order_id = oi.order_id and oi.order_status > 0 and oi.order_status < 9 AND DATEDIFF(curdate(),FROM_UNIXTIME(oi.add_time,\'%Y-%m-%d\')) <= 31 group by o.goods_id ) desc,sort_order,click_count desc,goods_id desc',
  ),
  'creat_html_domain' => 'http://www.ahf05.com/',
  'hot_keywords' => 'tablets under 200;http://www.dealsmachine.com/wholesale-core-tablet-under-200.html
3g tablet;http://www.dealsmachine.com/wholesale-3g-android-tablet.html
led bulbs;http://www.dealsmachine.com/wholesale-led-bulb.html
tactical flashlight;http://www.dealsmachine.com/wholesale-cree-tactical-flashlight.html
ccd camera;http://www.dealsmachine.com/wholesale-ccd-camera.html
mini keyboard;http://www.dealsmachine.com/wholesale-mini-keyboard.html
smart tv box;http://www.dealsmachine.com/wholesale-android-tv-box.html
power bank;http://www.dealsmachine.com/wholesale-power-bank.html
waterproof mp3 player;http://www.dealsmachine.com/wholesale-Waterproof-MP3-Player.html',
);
?>